/**
 * AUTO-GENERATED by scripts/translate-country-pillars.mjs — do not edit by hand.
 *
 * Phase B8 — Full 6-locale fan-out. Holds AI-translated copies of every
 * PillarLocalized field for the 4 non-native, non-English locales per country.
 * Merged into COUNTRY_PILLARS at module load via mergePillar() in countryPillars.ts.
 *
 * Reruns of the generator only fill missing keys; native + English copy in
 * countryPillars.ts always wins.
 */

import type { EuCountryCode, LocaleCode } from "./countries";

export type GeneratedLocalized = Partial<Record<LocaleCode, string>>;

export interface GeneratedPillar {
  hero?: {
    tagline?: GeneratedLocalized;
    lede?: GeneratedLocalized;
  };
  legalSystem?: GeneratedLocalized;
  howToFindLawyer?: GeneratedLocalized;
  feesAndAid?: GeneratedLocalized;
  barAssociation?: {
    membershipRules?: GeneratedLocalized;
  };
  crossBorderEU?: GeneratedLocalized;
  faqs?: Array<{ q?: GeneratedLocalized; a?: GeneratedLocalized }>;
}

export const GENERATED_PILLAR_TRANSLATIONS: Record<EuCountryCode, GeneratedPillar> = {
  "de": {
    "hero": {
      "tagline": {
        "fr": "Trouvez un Rechtsanwalt qualifié dans toute l'Allemagne — vérifié auprès du registre fédéral des avocats.",
        "es": "Encuentre un Rechtsanwalt cualificado en toda Alemania — verificado en el registro federal de abogados.",
        "it": "Trova un Rechtsanwalt qualificato in tutta la Germania — verificato rispetto all'albo federale.",
        "pt": "Encontre um Rechtsanwalt qualificado em toda a Alemanha — verificado no registo federal de advogados."
      },
      "lede": {
        "fr": "L'Allemagne compte environ 165 000 avocats agréés (Rechtsanwälte), tous réglementés par la Bundesrechtsanwaltsordnung (BRAO) et organisés en 27 chambres régionales d'avocats sous la Bundesrechtsanwaltskammer (BRAK) fédérale. Ce guide explique comment le système juridique allemand est structuré, comment trouver et mandater un avocat, quels honoraires attendre en vertu du RVG, et comment les avocats agréés dans l'UE peuvent exercer au-delà des frontières.",
        "es": "Alemania cuenta con aproximadamente 165.000 abogados colegiados (Rechtsanwälte), todos regulados por la Bundesrechtsanwaltsordnung (BRAO) y organizados en 27 colegios de abogados regionales bajo la Bundesrechtsanwaltskammer (BRAK) federal. Esta guía explica cómo se estructura el sistema legal alemán, cómo encontrar y contratar a un abogado, qué honorarios esperar según la RVG y cómo los abogados admitidos en la UE pueden ejercer en Alemania.",
        "it": "La Germania conta circa 165.000 avvocati abilitati (Rechtsanwälte), tutti regolamentati dalla Bundesrechtsanwaltsordnung (BRAO) e organizzati in 27 ordini regionali sotto la Bundesrechtsanwaltskammer (BRAK) federale. Questa guida spiega come è strutturato il sistema legale tedesco, come trovare e incaricare un avvocato, quali onorari aspettarsi ai sensi del RVG e come gli avvocati abilitati nell'UE possono esercitare la professione oltre confine.",
        "pt": "A Alemanha tem aproximadamente 165.000 advogados admitidos (Rechtsanwälte), todos regulados pela Bundesrechtsanwaltsordnung (BRAO) e organizados em 27 câmaras regionais de advogados sob a Bundesrechtsanwaltskammer (BRAK) federal. Este guia explica como o sistema jurídico alemão está estruturado, como encontrar e contratar um advogado, que honorários esperar sob o RVG e como os advogados admitidos na UE podem exercer a profissão além-fronteiras."
      }
    },
    "legalSystem": {
      "fr": "L'Allemagne est une juridiction de droit civil avec des statuts codifiés tels que le Bürgerliches Gesetzbuch (BGB) pour les affaires civiles, le Strafgesetzbuch (StGB) pour les affaires pénales, et le Handelsgesetzbuch (HGB) pour les affaires commerciales. La hiérarchie des tribunaux est divisée par sujet : les affaires civiles et pénales ordinaires passent par l'Amtsgericht → Landgericht → Oberlandesgericht → Bundesgerichtshof (BGH). Les branches spécialisées comprennent les tribunaux du travail (Arbeitsgericht), administratifs (Verwaltungsgericht), sociaux (Sozialgericht) et fiscaux (Finanzgericht), chacun avec sa propre cour fédérale suprême. Les questions constitutionnelles sont traitées par le Bundesverfassungsgericht à Karlsruhe. Les avocats agréés en Allemagne peuvent comparaître devant tous les tribunaux, à l'exception du BGH en matière civile, ce qui nécessite une Singularzulassung distincte.",
      "es": "Alemania es una jurisdicción de derecho civil con estatutos codificados como el Bürgerliches Gesetzbuch (BGB) para asuntos civiles, el Strafgesetzbuch (StGB) para asuntos penales y el Handelsgesetzbuch (HGB) para asuntos comerciales. La jerarquía judicial se divide por materia: los casos civiles y penales ordinarios pasan por Amtsgericht → Landgericht → Oberlandesgericht → Bundesgerichtshof (BGH). Las ramas especializadas incluyen los tribunales de Arbeitsgericht (laboral), Verwaltungsgericht (administrativo), Sozialgericht (social) y Finanzgericht (fiscal), cada uno con su propio tribunal federal supremo. Las cuestiones constitucionales van al Bundesverfassungsgericht en Karlsruhe. Los abogados admitidos en Alemania pueden comparecer ante todos los tribunales, excepto el BGH en asuntos civiles, que requiere una Singularzulassung separada.",
      "it": "La Germania è una giurisdizione di diritto civile con statuti codificati come il Bürgerliches Gesetzbuch (BGB) per le questioni civili, lo Strafgesetzbuch (StGB) per le questioni penali e l'Handelsgesetzbuch (HGB) per le questioni commerciali. La gerarchia dei tribunali è suddivisa per materia: i casi civili e penali ordinari passano attraverso Amtsgericht → Landgericht → Oberlandesgericht → Bundesgerichtshof (BGH). I rami specialistici includono i tribunali del lavoro (Arbeitsgericht), amministrativi (Verwaltungsgericht), sociali (Sozialgericht) e fiscali (Finanzgericht), ciascuno con il proprio tribunale federale di vertice. Le questioni costituzionali vanno al Bundesverfassungsgericht a Karlsruhe. Gli avvocati abilitati in Germania possono comparire dinanzi a tutti i tribunali, eccetto il BGH in materia civile, che richiede una separata Singularzulassung.",
      "pt": "A Alemanha é uma jurisdição de direito civil com estatutos codificados, como o Bürgerliches Gesetzbuch (BGB) para assuntos civis, o Strafgesetzbuch (StGB) para assuntos criminais e o Handelsgesetzbuch (HGB) para assuntos comerciais. A hierarquia dos tribunais é dividida por assunto: casos civis e criminais ordinários tramitam através de Amtsgericht → Landgericht → Oberlandesgericht → Bundesgerichtshof (BGH). Os ramos especializados incluem os tribunais de trabalho (Arbeitsgericht), administrativos (Verwaltungsgericht), sociais (Sozialgericht) e fiscais (Finanzgericht), cada um com o seu próprio tribunal federal de cúpula. As questões constitucionais vão para o Bundesverfassungsgericht em Karlsruhe. Os advogados admitidos na Alemanha podem comparecer perante todos os tribunais, exceto o BGH em matéria civil, que exige uma Singularzulassung separada."
    },
    "howToFindLawyer": {
      "fr": "Commencez par identifier le domaine de pratique pertinent — le droit allemand des avocats permet aux avocats de faire de la publicité pour des spécialisations (Fachanwalt) seulement après avoir réussi un examen distinct et démontré une expérience de cas, donc une désignation 'Fachanwalt für Familienrecht' ou 'Fachanwalt für Arbeitsrecht' est un signal fort. Vérifiez tout candidat par rapport au Bundesweites Amtliches Anwaltsverzeichnis officiel à l'adresse https://www.rechtsanwaltsregister.org. La plupart des cabinets allemands proposent une Erstberatung (consultation initiale) payante plafonnée à 190 € plus TVA par le §34 RVG, bien que beaucoup renoncent ou réduisent les honoraires pour les affaires claires. Apportez des documents écrits et une chronologie. Après la réunion, vous recevrez normalement une Vollmacht (procuration) et une convention d'honoraires (Vergütungsvereinbarung) à signer avant que le travail ne commence.",
      "es": "Comience identificando el área de práctica relevante — la ley de colegios de abogados alemana permite a los abogados anunciar especializaciones (Fachanwalt) solo después de aprobar un examen separado y demostrar experiencia en casos, por lo que una designación de 'Fachanwalt für Familienrecht' o 'Fachanwalt für Arbeitsrecht' es una señal fuerte. Verifique a cualquier candidato en el Bundesweites Amtliches Anwaltsverzeichnis oficial en https://www.rechtsanwaltsregister.org. La mayoría de las firmas alemanas ofrecen una Erstberatung (consulta inicial) pagada con un tope de 190 € más IVA según el §34 RVG, aunque muchas eximen o reducen la tarifa para asuntos claros. Traiga documentos escritos y una cronología. Después de la reunión, normalmente recibirá una Vollmacht (poder notarial) y un acuerdo de honorarios (Vergütungsvereinbarung) para firmar antes de que comience el trabajo.",
      "it": "Inizia identificando l'area di pratica pertinente — la legge tedesca sull'avvocatura consente agli avvocati di pubblicizzare specializzazioni (Fachanwalt) solo dopo aver superato un esame separato e aver dimostrato esperienza pratica, quindi la designazione di 'Fachanwalt für Familienrecht' o 'Fachanwalt für Arbeitsrecht' è un forte segnale. Verifica ogni candidato rispetto al Bundesweites Amtliches Anwaltsverzeichnis ufficiale all'indirizzo https://www.rechtsanwaltsregister.org. La maggior parte degli studi tedeschi offre una Erstberatung (consultazione iniziale) a pagamento, limitata a €190 più IVA ai sensi del §34 RVG, sebbene molti rinuncino o riducano la tariffa per questioni chiare. Porta documenti scritti e una cronologia. Dopo l'incontro riceverai normalmente una Vollmacht (procura) e un accordo sugli onorari (Vergütungsvereinbarung) da firmare prima che il lavoro inizi.",
      "pt": "Comece por identificar a área de prática relevante — a lei alemã de advogados permite que os advogados anunciem especializações (Fachanwalt) apenas após passarem num exame separado e demonstrarem experiência em casos, pelo que uma designação 'Fachanwalt für Familienrecht' ou 'Fachanwalt für Arbeitsrecht' é um forte sinal. Verifique qualquer candidato no Bundesweites Amtliches Anwaltsverzeichnis oficial em https://www.rechtsanwaltsregister.org. A maioria das firmas alemãs oferece uma Erstberatung (consulta inicial) paga, limitada a €190 mais IVA pelo §34 RVG, embora muitas dispensem ou reduzam a taxa para assuntos claros. Traga documentos escritos e uma cronologia. Após a reunião, normalmente receberá uma Vollmacht (procuração) e um acordo de honorários (Vergütungsvereinbarung) para assinar antes do início do trabalho."
    },
    "feesAndAid": {
      "fr": "Les honoraires d'avocat en Allemagne sont régis par le Rechtsanwaltsvergütungsgesetz (RVG). Les honoraires statutaires varient en fonction de la valeur de l'affaire (Gegenstandswert) et sont prévisibles — utile pour la budgétisation des litiges. Les avocats peuvent convenir d'honoraires plus élevés par écrit (Vergütungsvereinbarung), mais devant le tribunal, ils ne peuvent pas être inférieurs au taux du RVG. Les honoraires de succès sont largement interdits et ne sont autorisés que dans des cas étroits où le client ne pourrait pas autrement faire valoir une créance. Deux programmes d'aide basés sur les ressources existent : la Beratungshilfe couvre les conseils extrajudiciaires pour les clients à faible revenu avec un Berechtigungsschein de l'Amtsgericht, et la Prozesskostenhilfe (PKH) couvre les frais de justice et les honoraires d'avocat une fois qu'un procès est intenté. L'assurance de protection juridique (Rechtsschutzversicherung) est courante en Allemagne et de nombreuses polices couvrent les litiges du travail, de la circulation et de la location.",
      "es": "Los honorarios de los abogados en Alemania se rigen por la Rechtsanwaltsvergütungsgesetz (RVG). Los honorarios legales se ajustan al valor del asunto (Gegenstandswert) y son predecibles, lo que es útil para la presupuestación de litigios. Los abogados pueden acordar honorarios más altos por escrito (Vergütungsvereinbarung), pero en los tribunales no pueden ser inferiores a la tarifa de la RVG. Los honorarios condicionales están en gran medida prohibidos y solo se permiten en casos específicos en los que el cliente no podría hacer valer una reclamación de otra manera. Existen dos programas de ayuda basados en los recursos económicos: Beratungshilfe cubre el asesoramiento extrajudicial para clientes de bajos ingresos con un Berechtigungsschein del Amtsgericht, y Prozesskostenhilfe (PKH) cubre los costos judiciales y los honorarios de los abogados una vez que se presenta una demanda. El seguro de gastos legales (Rechtsschutzversicherung) es común en Alemania y muchas pólizas cubren disputas laborales, de tráfico y de arrendamiento.",
      "it": "Gli onorari degli avvocati in Germania sono regolati dal Rechtsanwaltsvergütungsgesetz (RVG). Le tariffe legali sono proporzionali al valore della controversia (Gegenstandswert) e sono prevedibili — utili per la pianificazione del budget del contenzioso. Gli avvocati possono concordare onorari più elevati per iscritto (Vergütungsvereinbarung), ma in tribunale non possono scendere al di sotto della tariffa RVG. Le parcelle di successo sono in gran parte proibite e consentite solo in casi specifici in cui il cliente non potrebbe altrimenti far valere un credito. Esistono due programmi di assistenza basati sul reddito: la Beratungshilfe copre la consulenza extragiudiziale per i clienti a basso reddito con un Berechtigungsschein dell'Amtsgericht, e la Prozesskostenhilfe (PKH) copre le spese processuali e gli onorari dell'avvocato una volta avviata una causa. L'assicurazione di tutela legale (Rechtsschutzversicherung) è comune in Germania e molte polizze coprono controversie in materia di lavoro, traffico e locazione.",
      "pt": "Os honorários dos advogados na Alemanha são regidos pela Rechtsanwaltsvergütungsgesetz (RVG). Os honorários estatutários aumentam com o valor da matéria (Gegenstandswert) e são previsíveis — úteis para o orçamento de litígios. Os advogados podem acordar honorários mais elevados por escrito (Vergütungsvereinbarung), mas em tribunal não podem ser inferiores à taxa RVG. Os honorários de contingência são largamente proibidos e só são permitidos em casos restritos onde o cliente não conseguiria, de outra forma, fazer valer uma reclamação. Existem dois programas de ajuda baseados em rendimentos: o Beratungshilfe cobre aconselhamento extrajudicial para clientes de baixos rendimentos com um Berechtigungsschein do Amtsgericht, e o Prozesskostenhilfe (PKH) cobre custos judiciais e honorários de advogados uma vez que um processo seja iniciado. O seguro de despesas legais (Rechtsschutzversicherung) é comum na Alemanha e muitas apólices cobrem disputas laborais, de trânsito e de arrendamento."
    },
    "barAssociation": {
      "membershipRules": {
        "fr": "Chaque avocat allemand doit appartenir à l'une des 27 Rechtsanwaltskammern régionales, qui à leur tour constituent la BRAK. L'admission exige les premier et deuxième examens d'État en droit (ou une qualification étrangère reconnue équivalente) ainsi qu'une preuve d'assurance responsabilité civile professionnelle obligatoire d'au moins 250 000 €. Le Berufsordnung (BORA) et le §43b BRAO limitent la publicité aux informations objectives et professionnelles — la publicité sensationnaliste ou comparative est illégale.",
        "es": "Todo abogado alemán debe pertenecer a una de las 27 Rechtsanwaltskammern regionales, que a su vez forman la BRAK. La admisión requiere los Primer y Segundo Exámenes Estatales de derecho (o una cualificación extranjera reconocida equivalente) más la prueba de un seguro de responsabilidad profesional obligatorio de al menos 250.000 €. La Berufsordnung (BORA) y el §43b BRAO restringen la publicidad a información objetiva y relacionada con la profesión; la publicidad sensacionalista o comparativa es ilegal.",
        "it": "Ogni avvocato tedesco deve appartenere a una delle 27 Rechtsanwaltskammern regionali, che a loro volta costituiscono la BRAK. L'ammissione richiede il Primo e il Secondo Esame di Stato in giurisprudenza (o una qualifica straniera equivalente riconosciuta) più la prova di un'assicurazione obbligatoria di responsabilità civile professionale di almeno €250.000. La Berufsordnung (BORA) e il §43b BRAO limitano la pubblicità a informazioni oggettive e professionali — la pubblicità sensazionalistica o comparativa è illegale.",
        "pt": "Todo advogado alemão deve pertencer a uma das 27 Rechtsanwaltskammern regionais, que por sua vez compõem a BRAK. A admissão exige os Primeiros e Segundos Exames Estatais em direito (ou uma qualificação estrangeira equivalente reconhecida), além de prova de seguro de responsabilidade profissional obrigatório de pelo menos €250.000. A Berufsordnung (BORA) e o §43b BRAO restringem a publicidade a informações objetivas e relacionadas com a profissão — publicidade sensacionalista ou comparativa é ilegal."
      }
    },
    "crossBorderEU": {
      "fr": "En vertu de la directive d'établissement 98/5/CE, les avocats admis dans tout État membre de l'UE peuvent exercer en Allemagne sous leur titre professionnel national (par exemple, 'avocat' ou 'abogado') après s'être inscrits auprès d'une Rechtsanwaltskammer régionale. Après trois ans de pratique effective et régulière du droit allemand, ils peuvent demander une admission complète en tant que Rechtsanwalt sans repasser l'examen d'État allemand. Les services transfrontaliers à court terme sont couverts par la directive sur les services 77/249/CEE — un avocat français peut, par exemple, comparaître à une seule audience allemande sous son titre national sans s'inscrire, à condition de travailler aux côtés d'un Einvernehmensanwalt admis localement lorsque le droit procédural l'exige.",
      "es": "Según la Directiva de Establecimiento 98/5/EC, los abogados admitidos en cualquier estado miembro de la UE pueden ejercer en Alemania bajo su título profesional de origen (por ejemplo, 'avocat' o 'abogado') después de registrarse en una Rechtsanwaltskammer regional. Después de tres años de práctica efectiva y regular en derecho alemán, pueden solicitar la admisión plena como Rechtsanwalt sin volver a presentarse al examen estatal alemán. Los servicios transfronterizos a corto plazo están cubiertos por la Directiva de Servicios 77/249/EEC; un avocat francés puede, por ejemplo, comparecer en una única audiencia alemana bajo su título de origen sin registrarse, siempre que trabaje junto a un Einvernehmensanwalt admitido localmente cuando lo exija la ley procesal.",
      "it": "Ai sensi della Direttiva di stabilimento 98/5/CE, gli avvocati abilitati in qualsiasi Stato membro dell'UE possono esercitare la professione in Germania con il loro titolo professionale del paese d'origine (ad esempio 'avocat' o 'abogado') dopo essersi registrati presso una Rechtsanwaltskammer regionale. Dopo tre anni di pratica effettiva e regolare nel diritto tedesco, possono richiedere la piena ammissione come Rechtsanwalt senza dover sostenere nuovamente l'esame di stato tedesco. I servizi transfrontalieri a breve termine sono coperti dalla Direttiva sui servizi 77/249/CEE — un avocat francese può, ad esempio, comparire in una singola udienza tedesca con il suo titolo d'origine senza registrarsi, a condizione che lavori a fianco di un Einvernehmensanwalt ammesso localmente, ove richiesto dal diritto processuale.",
      "pt": "Ao abrigo da Diretiva de Estabelecimento 98/5/CE, os advogados admitidos em qualquer Estado-Membro da UE podem exercer a profissão na Alemanha sob o seu título profissional de origem (por exemplo, 'avocat' ou 'abogado') após se registarem numa Rechtsanwaltskammer regional. Após três anos de prática efetiva e regular em direito alemão, podem solicitar a admissão plena como Rechtsanwalt sem repetir o exame estatal alemão. Os serviços transfronteiriços de curta duração são abrangidos pela Diretiva de Serviços 77/249/CEE — um avocat francês pode, por exemplo, comparecer numa única audiência alemã sob o seu título de origem sem se registar, desde que trabalhe em conjunto com um Einvernehmensanwalt admitido localmente, quando exigido pela lei processual."
    },
    "faqs": [
      {
        "q": {
          "fr": "Comment vérifier si un avocat allemand est réellement admis ?",
          "es": "¿Cómo puedo verificar si un abogado alemán está realmente colegiado?",
          "it": "Come posso verificare se un avvocato tedesco è effettivamente abilitato?",
          "pt": "Como verifico se um advogado alemão está realmente admitido?"
        },
        "a": {
          "fr": "Recherchez dans le Bundesweites Amtliches Anwaltsverzeichnis officiel à l'adresse rechtsanwaltsregister.org. Chaque Rechtsanwalt admis y est répertorié avec son adhésion à la Kammer et les tribunaux où il est admis.",
          "es": "Busque en el Bundesweites Amtliches Anwaltsverzeichnis oficial en rechtsanwaltsregister.org. Todo Rechtsanwalt colegiado figura allí con su membresía en la Kammer y los tribunales admitidos.",
          "it": "Cerca nel Bundesweites Amtliches Anwaltsverzeichnis ufficiale su rechtsanwaltsregister.org. Ogni Rechtsanwalt abilitato è elencato lì con la sua appartenenza alla Kammer e i tribunali ammessi.",
          "pt": "Pesquise no Bundesweites Amtliches Anwaltsverzeichnis oficial em rechtsanwaltsregister.org. Todo Rechtsanwalt admitido está listado lá com a sua filiação na Kammer e os tribunais admitidos."
        }
      },
      {
        "q": {
          "fr": "Combien coûte généralement une consultation initiale ?",
          "es": "¿Cuánto cuesta normalmente una consulta inicial?",
          "it": "Quanto costa tipicamente una consultazione iniziale?",
          "pt": "Quanto custa tipicamente uma consulta inicial?"
        },
        "a": {
          "fr": "Selon le §34 RVG, le plafond statutaire pour une consultation initiale avec un consommateur est de 190 € plus TVA. De nombreux cabinets facturent moins ou déduisent ces frais des travaux ultérieurs.",
          "es": "Según el §34 RVG, el límite legal para una consulta inicial con un consumidor es de 190 € más IVA. Muchas firmas cobran menos o acreditan la tarifa contra trabajos posteriores.",
          "it": "Ai sensi del §34 RVG, il limite legale per una consultazione iniziale con un consumatore è di €190 più IVA. Molti studi applicano tariffe inferiori o accreditano la tariffa su lavori successivi.",
          "pt": "Pelo §34 RVG, o limite estatutário para uma consulta inicial com um consumidor é de €190 mais IVA. Muitas firmas cobram menos ou creditam a taxa em trabalhos posteriores."
        }
      },
      {
        "q": {
          "fr": "Puis-je engager un avocat admis dans un autre pays de l'UE ?",
          "es": "¿Puedo contratar a un abogado admitido en otro país de la UE?",
          "it": "Posso assumere un avvocato abilitato in un altro paese dell'UE?",
          "pt": "Posso contratar um advogado admitido noutro país da UE?"
        },
        "a": {
          "fr": "Oui. Les avocats admis dans l'UE peuvent fournir des services transfrontaliers en Allemagne sous leur titre national (Dir. 77/249/CEE). Pour un établissement continu, ils s'inscrivent auprès d'une Rechtsanwaltskammer allemande en vertu de la Dir. 98/5/CE.",
          "es": "Sí. Los abogados admitidos en la UE pueden prestar servicios transfronterizos en Alemania bajo su título de origen (Dir. 77/249/EEC). Para el establecimiento continuo, se registran en una Rechtsanwaltskammer alemana según la Dir. 98/5/EC.",
          "it": "Sì. Gli avvocati abilitati nell'UE possono fornire servizi transfrontalieri in Germania con il loro titolo d'origine (Dir. 77/249/CEE). Per l'insediamento continuativo si registrano presso una Rechtsanwaltskammer tedesca ai sensi della Dir. 98/5/CE.",
          "pt": "Sim. Advogados admitidos na UE podem prestar serviços transfronteiriços na Alemanha sob o seu título de origem (Dir. 77/249/CEE). Para estabelecimento contínuo, registam-se numa Rechtsanwaltskammer alemã ao abrigo da Dir. 98/5/CE."
        }
      },
      {
        "q": {
          "fr": "Qu'est-ce qu'un Fachanwalt et vaut-il la peine d'en choisir un ?",
          "es": "¿Qué es un Fachanwalt y vale la pena elegir uno?",
          "it": "Cos'è un Fachanwalt e vale la pena sceglierne uno?",
          "pt": "O que é um Fachanwalt e vale a pena escolher um?"
        },
        "a": {
          "fr": "Un Fachanwalt est un titre de spécialiste réglementé par la FAO. Il exige une formation supplémentaire, un examen écrit et la preuve d'une pratique substantielle dans le domaine — un signal fort de la profondeur des connaissances en la matière.",
          "es": "Un Fachanwalt es un título de especialista regulado por la FAO. Requiere formación adicional, un examen escrito y prueba de una práctica sustancial en el campo, una fuerte señal de profundidad en la materia.",
          "it": "Un Fachanwalt è un titolo specialistico regolato dalla FAO. Richiede formazione aggiuntiva, un esame scritto e la prova di una pratica sostanziale nel campo — un forte segnale di profonda conoscenza della materia.",
          "pt": "Um Fachanwalt é um título de especialista regulado pela FAO. Exige formação adicional, um exame escrito e prova de prática substancial de casos na área — um forte sinal de profundidade na matéria."
        }
      },
      {
        "q": {
          "fr": "Mon assurance de protection juridique paiera-t-elle directement l'avocat ?",
          "es": "¿Mi seguro de gastos legales pagará directamente al abogado?",
          "it": "La mia assicurazione di tutela legale pagherà direttamente l'avvocato?",
          "pt": "O meu seguro de despesas legais pagará diretamente ao advogado?"
        },
        "a": {
          "fr": "La plupart des polices d'assurance Rechtsschutz allemandes délivrent une Deckungszusage (confirmation de couverture) sur demande et paient directement les honoraires RVG de l'avocat dans les limites convenues, sous réserve de la franchise de la police.",
          "es": "La mayoría de las pólizas de Rechtsschutz alemanas emiten una Deckungszusage (confirmación de cobertura) previa solicitud y pagan directamente los honorarios de la RVG del abogado dentro del alcance acordado, sujeto a la franquicia de la póliza.",
          "it": "La maggior parte delle polizze tedesche di Rechtsschutz rilascia una Deckungszusage (conferma di copertura) su richiesta e paga direttamente gli onorari RVG dell'avvocato entro l'ambito concordato, soggetto alla franchigia della polizza.",
          "pt": "A maioria das apólices de Rechtsschutz alemãs emite uma Deckungszusage (confirmação de cobertura) a pedido e paga os honorários RVG do advogado diretamente dentro do âmbito acordado, sujeito à franquia da apólice."
        }
      },
      {
        "q": {
          "fr": "Ai-je besoin d'un avocat pour les petites créances civiles ?",
          "es": "¿Necesito un abogado para reclamaciones civiles menores?",
          "it": "Ho bisogno di un avvocato per piccole controversie civili?",
          "pt": "Preciso de um advogado para pequenas ações cíveis?"
        },
        "a": {
          "fr": "Non. Devant l'Amtsgericht (créances jusqu'à 5 000 €), les parties peuvent comparaître sans avocat. Devant le Landgericht et les tribunaux supérieurs, la représentation par un Rechtsanwalt admis est obligatoire (Anwaltszwang).",
          "es": "No. Ante el Amtsgericht (reclamaciones de hasta 5.000 €), las partes pueden comparecer sin abogado. Ante el Landgericht y los tribunales superiores, la representación por un Rechtsanwalt colegiado es obligatoria (Anwaltszwang).",
          "it": "No. Davanti all'Amtsgericht (controversie fino a €5.000) le parti possono comparire senza avvocato. Davanti al Landgericht e ai tribunali superiori la rappresentanza da parte di un Rechtsanwalt abilitato è obbligatoria (Anwaltszwang).",
          "pt": "Não. Perante o Amtsgericht (ações até €5.000), as partes podem comparecer sem advogado. Perante o Landgericht e tribunais superiores, a representação por um Rechtsanwalt admitido é obrigatória (Anwaltszwang)."
        }
      }
    ]
  },
  "fr": {
    "hero": {
      "tagline": {
        "de": "Finden Sie einen registrierten Anwalt in ganz Frankreich – überprüft anhand der nationalen Liste des CNB.",
        "es": "Encuentre un avocat colegiado en toda Francia — verificado en el registro nacional del CNB.",
        "it": "Trova un avvocato iscritto in tutta la Francia — verificato rispetto all'albo nazionale del CNB.",
        "pt": "Encontre um advogado registado em toda a França — verificado no registo nacional do CNB."
      },
      "lede": {
        "de": "Frankreich hat ungefähr 75.000 Anwälte, die alle Mitglieder einer der 164 lokalen Anwaltskammern (barreaux) sind und national vom Conseil National des Barreaux (CNB) vertreten werden. Dieser Leitfaden erklärt, wie das französische Rechtssystem strukturiert ist, wie man einen Anwalt beauftragt, welche Gebühren und Prozesskostenhilfe (aide juridictionnelle) Sie erwarten können und wie in der EU zugelassene Anwälte in Frankreich praktizieren können.",
        "es": "Francia cuenta con aproximadamente 75.000 avocats, todos ellos miembros de uno de los 164 colegios de abogados locales (barreaux) y representados a nivel nacional por el Conseil National des Barreaux (CNB). Esta guía explica cómo está estructurado el sistema legal francés, cómo contratar a un avocat, qué honorarios y asistencia jurídica gratuita (aide juridictionnelle) puede esperar, y cómo los abogados admitidos en la UE pueden ejercer en Francia.",
        "it": "La Francia conta circa 75.000 avvocati, tutti membri di uno dei 164 ordini locali (barreaux) e rappresentati a livello nazionale dal Conseil National des Barreaux (CNB). Questa guida spiega come è strutturato il sistema legale francese, come incaricare un avvocato, quali onorari e assistenza legale (aide juridictionnelle) ci si può aspettare e come gli avvocati ammessi nell'UE possono esercitare in Francia.",
        "pt": "A França tem aproximadamente 75.000 advogados, todos membros de uma das 164 ordens locais (barreaux) e representados nacionalmente pelo Conseil National des Barreaux (CNB). Este guia explica como o sistema jurídico francês está estruturado, como contratar um advogado, que honorários e assistência jurídica (aide juridictionnelle) pode esperar, e como os advogados admitidos na UE podem exercer em França."
      }
    },
    "legalSystem": {
      "de": "Frankreich ist eine Zivilrechtsordnung, die auf kodifizierten Texten basiert – der Code civil, Code de commerce, Code pénal und Code du travail sind die am häufigsten zitierten in der täglichen Praxis. Die Gerichtsordnung (ordre judiciaire) behandelt Zivil- und Strafsachen über das Tribunal judiciaire → Cour d'appel → Cour de cassation. Eine parallele Verwaltungsordnung (ordre administratif) entscheidet über Streitigkeiten gegen den Staat über Tribunal administratif → Cour administrative d'appel → Conseil d'État. Der Conseil constitutionnel prüft Verfassungsfragen, und das Tribunal des conflits löst Zuständigkeitskonflikte zwischen den beiden Ordnungen. Anwälte dürfen vor jedem erstinstanzlichen und Berufungsgericht plädieren, aber eine separate Gruppe – avocats au Conseil d'État et à la Cour de cassation – hat das Monopol auf die Vertretung vor diesen beiden obersten Gerichten.",
      "es": "Francia es una jurisdicción de derecho civil estructurada en torno a textos codificados — siendo el Code civil, el Code de commerce, el Code pénal y el Code du travail los más citados en la práctica diaria. El orden judicial (ordre judiciaire) tramita casos civiles y penales a través del Tribunal judiciaire → Cour d'appel → Cour de cassation. Un orden administrativo paralelo (ordre administratif) conoce de los litigios contra el Estado a través del Tribunal administratif → Cour administrative d'appel → Conseil d'État. El Conseil constitutionnel revisa las cuestiones constitucionales, y el Tribunal des conflits resuelve los conflictos de jurisdicción entre los dos órdenes. Los avocats pueden litigar ante todos los tribunales de primera instancia y de apelación, pero un grupo separado — avocats au Conseil d'État et à la Cour de cassation — ostenta el monopolio de la representación ante esos dos tribunales superiores.",
      "it": "La Francia è una giurisdizione di diritto civile strutturata attorno a testi codificati — il Code civil, il Code de commerce, il Code pénal e il Code du travail sono i più citati nella pratica quotidiana. L'ordine giudiziario (ordre judiciaire) gestisce i casi civili e penali attraverso il Tribunal judiciaire → Cour d'appel → Cour de cassation. Un ordine amministrativo parallelo (ordre administratif) si occupa delle controversie contro lo Stato tramite il Tribunal administratif → Cour administrative d'appel → Conseil d'État. Il Conseil constitutionnel esamina le questioni costituzionali e il Tribunal des conflits risolve i conflitti di giurisdizione tra i due ordini. Gli avvocati possono patrocinare dinanzi a ogni tribunale di primo grado e d'appello, ma una coorte separata — avocats au Conseil d'État et à la Cour de cassation — detiene il monopolio della rappresentanza dinanzi a queste due corti supreme.",
      "pt": "A França é uma jurisdição de direito civil estruturada em torno de textos codificados — sendo o Code civil, Code de commerce, Code pénal e Code du travail os mais citados na prática diária. A ordem judicial (ordre judiciaire) trata de casos civis e criminais através do Tribunal judiciaire → Cour d'appel → Cour de cassation. Uma ordem administrativa paralela (ordre administratif) ouve litígios contra o Estado via Tribunal administratif → Cour administrative d'appel → Conseil d'État. O Conseil constitutionnel revê questões constitucionais, e o Tribunal des conflits resolve conflitos de jurisdição entre as duas ordens. Os advogados podem pleitear perante todos os tribunais de primeira instância e de recurso, mas um grupo separado — avocats au Conseil d'État et à la Cour de cassation — detém o monopólio da representação perante esses dois tribunais superiores."
    },
    "howToFindLawyer": {
      "de": "Beginnen Sie mit der Identifizierung des Rechtsgebiets und wählen Sie, wo möglich, einen Anwalt mit einer anerkannten mention de spécialisation (z.B. droit du travail, droit de la famille, droit fiscal) – diese Spezialisierungen werden vom CNB nach vierjähriger Praxis und einer Fachprüfung verliehen. Überprüfen Sie jeden Kandidaten über das Online-Verzeichnis des CNB unter https://www.cnb.avocat.fr/fr/annuaire-des-avocats-de-france. Eine Erstberatung (consultation initiale) kostet typischerweise zwischen 80 € und 250 € und muss Gegenstand einer schriftlichen Honorarvereinbarung (convention d'honoraires) sein, die nun gemäß Artikel 10 des Loi du 31 décembre 1971 obligatorisch ist. Der Anwalt wird normalerweise eine Vollmacht (mandat ad litem) und entweder ein Pauschalhonorar, einen Stundensatz oder ein teilweises Erfolgshonorar (honoraire de résultat) verlangen, das in Frankreich als Ergänzung zu einem Basishonorar, aber nicht als alleinige Vergütung zulässig ist.",
      "es": "Comience identificando el área de práctica y, cuando sea posible, elija un avocat que posea una mention de spécialisation reconocida (por ejemplo, droit du travail, droit de la famille, droit fiscal) — estas especializaciones son otorgadas por el CNB después de cuatro años de práctica y un examen de especialista. Verifique a cualquier candidato a través del annuaire en línea del CNB en https://www.cnb.avocat.fr/fr/annuaire-des-avocats-de-france. Una primera consulta (consultation initiale) suele tener un precio de entre 80 y 250 euros y debe ser objeto de un acuerdo de honorarios por escrito (convention d'honoraires), ahora obligatorio según el artículo 10 de la Loi du 31 décembre 1971. El avocat normalmente solicitará un poder (mandat ad litem) y, o bien una tarifa fija, una tarifa por hora, o una tarifa de éxito parcial (honoraire de résultat), que está permitida en Francia como complemento a una tarifa base pero no como única compensación.",
      "it": "Inizia identificando l'area di pratica e, ove possibile, scegli un avvocato in possesso di una mention de spécialisation riconosciuta (es. droit du travail, droit de la famille, droit fiscal) — queste specializzazioni sono rilasciate dal CNB dopo quattro anni di pratica e un esame specialistico. Verifica qualsiasi candidato tramite l'annuario online del CNB all'indirizzo https://www.cnb.avocat.fr/fr/annuaire-des-avocats-de-france. Una prima consultazione (consultation initiale) ha tipicamente un costo compreso tra €80 e €250 e deve essere oggetto di un accordo scritto sugli onorari (convention d'honoraires), ora obbligatorio ai sensi dell'articolo 10 della Loi du 31 décembre 1971. L'avvocato richiederà normalmente una procura (mandat ad litem) e un onorario fisso, una tariffa oraria o un onorario di successo parziale (honoraire de résultat), che è consentito in Francia come complemento a un onorario base ma non come unica remunerazione.",
      "pt": "Comece por identificar a área de prática e, sempre que possível, escolha um advogado com uma mention de spécialisation reconhecida (e.g. droit du travail, droit de la famille, droit fiscal) — estas especializações são atribuídas pelo CNB após quatro anos de prática e um exame de especialista. Verifique qualquer candidato através do annuaire online do CNB em https://www.cnb.avocat.fr/fr/annuaire-des-avocats-de-france. Uma primeira consulta (consultation initiale) tem um preço típico entre €80 e €250 e deve ser objeto de um acordo de honorários por escrito (convention d'honoraires), agora obrigatório nos termos do artigo 10 da Loi du 31 décembre 1971. O advogado normalmente solicitará uma procuração (mandat ad litem) e honorários fixos, uma taxa horária, ou uma taxa de sucesso parcial (honoraire de résultat), que é permitida em França como complemento a uma taxa base, mas não como única compensação."
    },
    "feesAndAid": {
      "de": "Anwaltsgebühren in Frankreich werden frei verhandelt, müssen aber in einer schriftlichen convention d'honoraires aufgeführt sein. Stundensätze liegen typischerweise zwischen 150 € in regionalen Kanzleien und über 600 € in Pariser Wirtschaftskanzleien. Reine Erfolgshonorare (pacte de quota litis) sind verboten; teilweise Erfolgshonorare sind erlaubt. Aide juridictionnelle ist das einkommensabhängige Prozesskostenhilfesystem: Ab 2026 gilt die volle Deckung bis zu einem Referenzeinkommen von etwa 1.074 € pro Monat für einen alleinstehenden Erwachsenen, mit teilweiser Deckung auf einer gleitenden Skala bis zu etwa 1.612 €. Der Antrag (formulaire Cerfa 16146) wird beim bureau d'aide juridictionnelle des zuständigen tribunal judiciaire eingereicht. Rechtsschutzversicherungen – häufig in Haus- oder Autoversicherungen gebündelt – finanzieren auch viele Arbeits-, Verbraucher- und Nachbarschaftsstreitigkeiten.",
      "es": "Los honorarios de los avocats en Francia se negocian libremente, pero deben figurar en una convention d'honoraires por escrito. Las tarifas por hora suelen oscilar entre 150 euros en despachos regionales y más de 600 euros en despachos de negocios de París. La contingencia pura (pacte de quota litis) está prohibida; se permiten las tarifas de resultado parcial. La aide juridictionnelle es el sistema de asistencia jurídica gratuita basado en los recursos económicos: a partir de 2026, la cobertura total se aplica hasta un ingreso de referencia de alrededor de 1.074 euros al mes para un adulto soltero, con cobertura parcial en una escala móvil hasta aproximadamente 1.612 euros. La solicitud (formulaire Cerfa 16146) se presenta en la bureau d'aide juridictionnelle del tribunal judiciaire competente. Las pólizas de protection juridique —frecuentemente incluidas en los seguros de hogar o de coche— también financian muchos litigios laborales, de consumo y vecinales.",
      "it": "Gli onorari degli avvocati in Francia sono liberamente negoziati ma devono figurare in una convention d'honoraires scritta. Le tariffe orarie variano tipicamente da €150 negli studi regionali a oltre €600 negli studi di affari di Parigi. La pura contingenza (pacte de quota litis) è proibita; gli onorari di risultato parziale sono consentiti. L'aide juridictionnelle è il regime di assistenza legale basato sul reddito: a partire dal 2026, la copertura completa si applica fino a un reddito di riferimento di circa €1.074 al mese per un adulto single, con copertura parziale su scala mobile fino a circa €1.612. La domanda (formulaire Cerfa 16146) viene presentata presso il bureau d'aide juridictionnelle del tribunale giudiziario competente. Le polizze di protection juridique — spesso abbinate all'assicurazione sulla casa o sull'auto — finanziano anche molte controversie in materia di lavoro, consumo e vicinato.",
      "pt": "Os honorários dos advogados em França são livremente negociados, mas devem constar de uma convention d'honoraires por escrito. As taxas horárias variam tipicamente de €150 em escritórios regionais a mais de €600 em escritórios de negócios em Paris. A contingência pura (pacte de quota litis) é proibida; as taxas de resultado parciais são permitidas. A Aide juridictionnelle é o regime de assistência jurídica com base nos rendimentos: a partir de 2026, a cobertura total aplica-se até um rendimento de referência de cerca de €1.074 por mês para um adulto solteiro, com cobertura parcial numa escala progressiva até aproximadamente €1.612. O pedido (formulaire Cerfa 16146) é apresentado no bureau d'aide juridictionnelle do tribunal judiciaire competente. As apólices de protection juridique — frequentemente incluídas em seguros de casa ou automóvel — também financiam muitos litígios laborais, de consumo e de vizinhança."
    },
    "barAssociation": {
      "membershipRules": {
        "de": "Jeder praktizierende Anwalt muss bei einer der 164 barreaux eingeschrieben sein und eine obligatorische Berufshaftpflichtversicherung (RC professionnelle) sowie eine finanzielle Garantie für Klientengelder (garantie de représentation des fonds) besitzen. Das Règlement Intérieur National (RIN) regelt Ethik, Interessenkonflikte, Werbung und das strenge Berufsgeheimnis (secret professionnel), das gemäß Artikel 226-13 des Code pénal strafrechtlich geschützt ist. Werbung ist gemäß Artikel 10.2 des RIN erlaubt, sofern sie würdevoll, korrekt ist und keine Kundenreferenzen enthält.",
        "es": "Todo avocat en ejercicio debe estar inscrito en uno de los 164 barreaux y contar con un seguro de responsabilidad profesional obligatorio (RC professionnelle) más una garantía financiera para los fondos de los clientes (garantie de représentation des fonds). El Règlement Intérieur National (RIN) rige la ética, los conflictos de intereses, la publicidad y el estricto secreto profesional (secret professionnel) que, según el artículo 226-13 del Code pénal, está protegido penalmente. La publicidad está permitida según el artículo 10.2 del RIN siempre que sea digna, precisa y no incluya testimonios de clientes.",
        "it": "Ogni avvocato praticante deve essere iscritto a uno dei 164 barreaux e avere un'assicurazione obbligatoria di responsabilità civile professionale (RC professionnelle) più una garanzia finanziaria per i fondi dei clienti (garantie de représentation des fonds). Il Règlement Intérieur National (RIN) disciplina l'etica, i conflitti di interesse, la pubblicità e il rigoroso segreto professionale (secret professionnel) che, ai sensi dell'articolo 226-13 del Code pénal, è penalmente protetto. La pubblicità è consentita ai sensi dell'articolo 10.2 del RIN a condizione che sia dignitosa, accurata e non includa testimonianze di clienti.",
        "pt": "Todo advogado em exercício deve estar inscrito num dos 164 barreaux e possuir seguro de responsabilidade civil profissional obrigatório (RC professionnelle), além de uma garantia financeira para fundos de clientes (garantie de représentation des fonds). O Règlement Intérieur National (RIN) rege a ética, conflitos de interesse, publicidade e o rigoroso segredo profissional (secret professionnel) que, nos termos do artigo 226-13 do Code pénal, é criminalmente protegido. A publicidade é permitida nos termos do artigo 10.2 do RIN, desde que seja digna, precisa e não inclua testemunhos de clientes."
      }
    },
    "crossBorderEU": {
      "de": "Gemäß der Niederlassungsrichtlinie 98/5/EG, umgesetzt durch das Loi du 31 décembre 1971 (Art. 83 ff.), dürfen in der EU zugelassene Anwälte in Frankreich unter ihrem Heimattitel (z.B. Rechtsanwalt, abogado, avvocato) praktizieren, nachdem sie sich bei einer französischen barreau registriert haben. Nach drei Jahren effektiver und regelmäßiger Praxis im französischen Recht können sie die volle Zulassung als avocat beantragen, ohne die CAPA erneut ablegen zu müssen. Kurzfristige grenzüberschreitende Dienstleistungen werden durch die Richtlinie 77/249/EWG abgedeckt: Ein ausländischer EU-Anwalt kann beispielsweise eine einzelne Anhörung in Frankreich unter seinem Heimattitel in Absprache mit einem lokal eingeschriebenen Anwalt durchführen, wo eine obligatorische Vertretung gilt.",
      "es": "Según la Directiva de Establecimiento 98/5/CE, transpuesta por la Loi du 31 décembre 1971 (art. 83 y ss.), los abogados admitidos en la UE pueden ejercer en Francia con su título de origen (por ejemplo, Rechtsanwalt, abogado, avvocato) después de registrarse en un barreau francés. Después de tres años de práctica efectiva y regular en derecho francés, pueden solicitar la admisión plena como avocat sin volver a presentarse al CAPA. Los servicios transfronterizos a corto plazo están cubiertos por la Directiva 77/249/CEE: un abogado extranjero de la UE puede, por ejemplo, litigar en una única audiencia en Francia con su título de origen, en coordinación con un avocat inscrito localmente cuando la representación sea obligatoria.",
      "it": "Ai sensi della Direttiva di stabilimento 98/5/CE, recepita dalla Loi du 31 décembre 1971 (art. 83 e segg.), gli avvocati ammessi nell'UE possono esercitare in Francia con il loro titolo di origine (es. Rechtsanwalt, abogado, avvocato) dopo essersi registrati presso un barreau francese. Dopo tre anni di pratica effettiva e regolare nel diritto francese, possono richiedere la piena ammissione come avocat senza ripetere il CAPA. I servizi transfrontalieri a breve termine sono coperti dalla Direttiva 77/249/CEE: un avvocato straniero dell'UE può, ad esempio, patrocinare una singola udienza in Francia con il proprio titolo di origine, in coordinamento con un avvocato iscritto localmente laddove sia obbligatoria la rappresentanza.",
      "pt": "Nos termos da Diretiva de Estabelecimento 98/5/CE, transposta pela Loi du 31 décembre 1971 (art. 83 e segs.), os advogados admitidos na UE podem exercer em França sob o seu título de origem (e.g. Rechtsanwalt, abogado, avvocato) após se registarem num barreau francês. Após três anos de prática efetiva e regular em direito francês, podem solicitar a admissão plena como advogado sem repetir o CAPA. Os serviços transfronteiriços de curta duração são abrangidos pela Diretiva 77/249/CEE: um advogado estrangeiro da UE pode, por exemplo, pleitear numa única audiência em França sob o seu título de origem, em coordenação com um advogado inscrito localmente onde a representação obrigatória se aplica."
    },
    "faqs": [
      {
        "q": {
          "de": "Wie überprüfe ich, ob ein französischer Anwalt tatsächlich ein avocat ist?",
          "es": "¿Cómo verifico que un abogado francés es realmente un avocat?",
          "it": "Come posso verificare che un avvocato francese sia effettivamente un avocat?",
          "pt": "Como verifico se um advogado francês é realmente um avocat?"
        },
        "a": {
          "de": "Suchen Sie im nationalen Verzeichnis des CNB unter cnb.avocat.fr. Jeder praktizierende Anwalt ist dort mit seiner barreau und eventuellen Spezialisierungen aufgeführt.",
          "es": "Busque en el annuaire nacional del CNB en cnb.avocat.fr. Todo avocat en ejercicio figura con su barreau y cualquier especialización.",
          "it": "Cerca nell'annuario nazionale del CNB su cnb.avocat.fr. Ogni avvocato praticante è elencato con il proprio barreau e le eventuali specializzazioni.",
          "pt": "Pesquise o annuaire nacional do CNB em cnb.avocat.fr. Todo advogado em exercício está listado com o seu barreau e quaisquer especializações."
        }
      },
      {
        "q": {
          "de": "Ist eine schriftliche Honorarvereinbarung obligatorisch?",
          "es": "¿Es obligatorio un acuerdo de honorarios por escrito?",
          "it": "È obbligatorio un accordo scritto sugli onorari?",
          "pt": "É obrigatório um acordo de honorários por escrito?"
        },
        "a": {
          "de": "Ja. Seit 2015 verlangt Artikel 10 des Loi du 31 décembre 1971 eine schriftliche convention d'honoraires für jedes Mandat, außer in dringenden Angelegenheiten.",
          "es": "Sí. Desde 2015, el artículo 10 de la Loi du 31 décembre 1971 exige una convention d'honoraires por escrito para cada encargo, salvo en asuntos urgentes.",
          "it": "Sì. Dal 2015 l'articolo 10 della Loi du 31 décembre 1971 richiede una convention d'honoraires scritta per ogni incarico, salvo per questioni urgenti.",
          "pt": "Sim. Desde 2015, o artigo 10 da Loi du 31 décembre 1971 exige uma convention d'honoraires por escrito para cada mandato, exceto em casos urgentes."
        }
      },
      {
        "q": {
          "de": "Wer hat Anspruch auf aide juridictionnelle?",
          "es": "¿Quién puede optar a la aide juridictionnelle?",
          "it": "Chi ha diritto all'aide juridictionnelle?",
          "pt": "Quem se qualifica para a aide juridictionnelle?"
        },
        "a": {
          "de": "Haushalte, deren revenu fiscal de référence unter dem gesetzlichen Schwellenwert liegt – etwa 1.074 €/Monat für einen alleinstehenden Erwachsenen im Jahr 2026 – haben Anspruch auf volle Hilfe, mit teilweiser Hilfe auf einer gleitenden Skala.",
          "es": "Los hogares por debajo del umbral legal de revenu fiscal de référence —alrededor de 1.074 €/mes para un adulto soltero en 2026— pueden optar a la ayuda completa, con ayuda parcial en una escala móvil.",
          "it": "I nuclei familiari al di sotto della soglia legale di revenu fiscal de référence — circa €1.074/mese per un adulto single nel 2026 — hanno diritto all'assistenza completa, con assistenza parziale su scala mobile.",
          "pt": "Agregados familiares abaixo do limiar legal de revenu fiscal de référence — cerca de €1.074/mês para um adulto solteiro em 2026 — qualificam-se para assistência total, com assistência parcial numa escala progressiva."
        }
      },
      {
        "q": {
          "de": "Kann ich einen in einem anderen EU-Land zugelassenen Anwalt beauftragen?",
          "es": "¿Puedo contratar a un abogado admitido en otro país de la UE?",
          "it": "Posso incaricare un avvocato ammesso in un altro paese dell'UE?",
          "pt": "Posso contratar um advogado admitido noutro país da UE?"
        },
        "a": {
          "de": "Ja. Die EU-Vorschriften (Richtlinien 77/249/EWG und 98/5/EG) erlauben grenzüberschreitende Dienstleistungen und, nach Registrierung bei einer französischen barreau, eine dauerhafte Praxis.",
          "es": "Sí. Las normas de la UE (Directivas 77/249/CEE y 98/5/CE) permiten los servicios transfronterizos y, tras el registro en un barreau francés, la práctica permanente.",
          "it": "Sì. Le norme dell'UE (Direttive 77/249/CEE e 98/5/CE) consentono servizi transfrontalieri e, dopo la registrazione presso un barreau francese, la pratica permanente.",
          "pt": "Sim. As regras da UE (Diretivas 77/249/CEE e 98/5/CE) permitem serviços transfronteiriços e, após o registo num barreau francês, a prática permanente."
        }
      },
      {
        "q": {
          "de": "Benötige ich für jedes Gericht einen Anwalt?",
          "es": "¿Necesito un avocat para cada tribunal?",
          "it": "Ho bisogno di un avocat per ogni tribunale?",
          "pt": "Preciso de um advogado para todos os tribunais?"
        },
        "a": {
          "de": "Nein. Die Vertretung ist vor dem conseil de prud'hommes, tribunaux de proximité (unter 10.000 €) und einigen Handelsangelegenheiten optional, aber vor dem tribunal judiciaire über 10.000 € und vor allen Berufungsgerichten obligatorisch.",
          "es": "No. La representación es opcional ante el conseil de prud'hommes, los tribunaux de proximité (menos de 10.000 €) y algunos asuntos comerciales, pero obligatoria ante el tribunal judiciaire por encima de 10.000 € y ante todos los tribunales de apelación.",
          "it": "No. La rappresentanza è facoltativa dinanzi al conseil de prud'hommes, ai tribunaux de proximité (sotto i €10.000) e in alcune questioni commerciali, ma obbligatoria dinanzi al tribunal judiciaire sopra i €10.000 e dinanzi a tutte le corti d'appello.",
          "pt": "Não. A representação é opcional perante o conseil de prud'hommes, tribunaux de proximité (abaixo de €10.000) e algumas questões comerciais, mas obrigatória perante o tribunal judiciaire acima de €10.000 e perante todos os tribunais de recurso."
        }
      },
      {
        "q": {
          "de": "Können Anwälte ein Erfolgshonorar verlangen?",
          "es": "¿Pueden los avocats cobrar una tarifa de éxito?",
          "it": "Gli avocats possono addebitare un onorario di successo?",
          "pt": "Os advogados podem cobrar uma taxa de sucesso?"
        },
        "a": {
          "de": "Ja, aber nur als Ergänzung zu einem Basishonorar. Eine rein erfolgsabhängige Vereinbarung (pacte de quota litis) ist nach Artikel 10 des Gesetzes von 1971 verboten.",
          "es": "Sí, pero solo como complemento a una tarifa base. Un acuerdo puramente contingente (pacte de quota litis) está prohibido por el artículo 10 de la ley de 1971.",
          "it": "Sì, ma solo come complemento a un onorario base. Un accordo puramente basato sulla contingenza (pacte de quota litis) è proibito dall'articolo 10 della legge del 1971.",
          "pt": "Sim, mas apenas como complemento a uma taxa base. Um acordo puramente baseado em contingência (pacte de quota litis) é proibido pelo artigo 10 da lei de 1971."
        }
      }
    ]
  },
  "es": {
    "hero": {
      "tagline": {
        "de": "Finden Sie einen registrierten Abogado in ganz Spanien – verifiziert durch den Generalrat der spanischen Anwaltschaft.",
        "fr": "Trouvez un abogado inscrit dans toute l'Espagne — vérifié par le Conseil Général des Avocats Espagnols.",
        "it": "Trova un abogado registrato in tutta la Spagna — verificato tramite il Consiglio Generale degli Avvocati Spagnoli."
      },
      "lede": {
        "de": "Spanien hat über 150.000 praktizierende Abogados, die in 83 regionalen Colegios de la Abogacía unter dem Consejo General de la Abogacía Española (CGAE) organisiert sind. Dieser Leitfaden behandelt die Struktur des spanischen Justizsystems, wie man einen Abogado beauftragt, die Regeln für Gebühren und Prozesskostenhilfe (justicia gratuita) sowie die grenzüberschreitende Tätigkeit von EU-Anwälten.",
        "fr": "L'Espagne compte plus de 150,000 abogados en exercice, organisés en 83 Colegios de la Abogacía provinciaux sous l'égide du Consejo General de la Abogacía Española (CGAE). Ce guide couvre la structure du système judiciaire espagnol, la manière de mandater un abogado, les règles relatives aux honoraires et à l'aide juridictionnelle (justicia gratuita), ainsi que la pratique transfrontalière des avocats de l'UE.",
        "it": "La Spagna conta più di 150.000 abogados praticanti, organizzati in 83 Colegios de la Abogacía provinciali sotto il Consejo General de la Abogacía Española (CGAE). Questa guida illustra la struttura del sistema giudiziario spagnolo, come incaricare un abogado, le norme in materia di onorari e patrocinio a spese dello Stato (justicia gratuita), e la pratica transfrontaliera degli avvocati dell'UE."
      }
    },
    "legalSystem": {
      "de": "Spanien ist ein Zivilrechtssystem, dessen Hauptgesetze der Código Civil, der Código Penal, die Ley de Enjuiciamiento Civil und die Ley de Enjuiciamiento Criminal sind. Die Justiz ist sachlich in vier Gerichtsbarkeiten unterteilt – Zivil-, Straf-, Verwaltungs- (contencioso-administrativo) und Sozialrecht (labour) – die jeweils über Juzgado → Audiencia Provincial (oder Äquivalent) → Tribunal Superior de Justicia der autonomen Gemeinschaft → Tribunal Supremo aufsteigen. Das Tribunal Constitucional prüft Verfassungsrechte mittels des recurso de amparo. Die Prozessvertretung erfordert in der Regel sowohl einen Abogado (Rechtsbeistand) als auch einen Procurador (Gerichtsbevollmächtigten) vor höheren Gerichten, obwohl seit der Reform von 2009 ein einziger Abogado für viele erstinstanzliche Angelegenheiten ausreicht.",
      "fr": "L'Espagne est une juridiction de droit civil dont les principaux codes sont le Código Civil, le Código Penal, la Ley de Enjuiciamiento Civil et la Ley de Enjuiciamiento Criminal. Le pouvoir judiciaire est divisé par matière en quatre ordres — civil, pénal, contencioso-administrativo et social (travail) — chacun progressant de Juzgado → Audiencia Provincial (ou équivalent) → Tribunal Superior de Justicia de la communauté autonome → Tribunal Supremo. Le Tribunal Constitucional examine les droits constitutionnels via le recurso de amparo. La représentation procédurale requiert généralement à la fois un abogado (défense juridique) et un procurador (agent judiciaire) devant les juridictions supérieures, bien qu'un seul abogado suffise pour de nombreuses affaires de première instance depuis la réforme de 2009.",
      "it": "La Spagna è una giurisdizione di diritto civile i cui codici principali sono il Código Civil, il Código Penal, la Ley de Enjuiciamiento Civil e la Ley de Enjuiciamiento Criminal. La magistratura è suddivisa per materia in quattro ordini — civile, penale, contencioso-administrativo e sociale (lavoro) — ciascuno con un'organizzazione gerarchica che va dal Juzgado → Audiencia Provincial (o equivalente) → Tribunal Superior de Justicia della comunità autonoma → Tribunal Supremo. Il Tribunal Constitucional esamina i diritti costituzionali tramite il recurso de amparo. La rappresentanza processuale richiede tipicamente sia un abogado (rappresentanza legale) che un procurador (agente di tribunale) dinanzi ai tribunali superiori, sebbene un singolo abogado sia sufficiente per molte questioni di primo grado dalla riforma del 2009."
    },
    "howToFindLawyer": {
      "de": "Beginnen Sie mit der Identifizierung des Rechtsgebiets und überprüfen Sie die Registrierung des Abogados im Censo de Letrados seines Colegio (z.B. ICAM für Madrid, ICAB für Barcelona). Die meisten Colegios veröffentlichen eine kostenlose Online-Suche; der CGAE konsolidiert die Einträge unter https://www.abogacia.es. Erstberatungen kosten üblicherweise zwischen €60 und €200, und der Abogado muss Ihnen gemäß Artikel 13 des Estatuto General de la Abogacía Española (Real Decreto 135/2021) einen presupuesto (schriftlicher Kostenvoranschlag) und eine hoja de encargo (Mandatsvereinbarung) aushändigen. Viele Colegios betreiben einen Servicio de Orientación Jurídica (SOJ), wo Bürger kostenlose vorläufige Beratung erhalten können, bevor sie justicia gratuita beantragen.",
      "fr": "Commencez par identifier le domaine de pratique et vérifiez l'inscription de l'abogado dans le Censo de Letrados de son Colegio (par exemple, ICAM pour Madrid, ICAB pour Barcelone). La plupart des colegios publient un annuaire en ligne gratuit ; le CGAE consolide les listes sur https://www.abogacia.es. Les consultations initiales sont généralement tarifées entre €60 et €200 et l'abogado doit vous fournir un presupuesto (estimation écrite des honoraires) et une hoja de encargo (lettre de mission) en vertu de l'article 13 de l'Estatuto General de la Abogacía Española (Real Decreto 135/2021). De nombreux colegios gèrent un Servicio de Orientación Jurídica (SOJ) où les citoyens peuvent obtenir des conseils préliminaires gratuits avant de demander la justicia gratuita.",
      "it": "Inizia identificando l'area di pratica e verifica l'iscrizione dell'abogado nel Censo de Letrados del loro Colegio (es. ICAM per Madrid, ICAB per Barcellona). La maggior parte dei colegios pubblica una ricerca online gratuita; il CGAE consolida gli elenchi su https://www.abogacia.es. Le consultazioni iniziali sono comunemente prezzate tra €60 e €200 e l'abogado deve fornirti un presupuesto (preventivo scritto degli onorari) e un'hoja de encargo (lettera di incarico) ai sensi dell'articolo 13 dello Estatuto General de la Abogacía Española (Real Decreto 135/2021). Molti colegios gestiscono un Servicio de Orientación Jurídica (SOJ) dove i cittadini possono ottenere una consulenza preliminare gratuita prima di richiedere la justicia gratuita."
    },
    "feesAndAid": {
      "de": "Gebühren werden in Spanien seit der Abschaffung der verbindlichen Gebührentabellen durch die Ley Ómnibus 25/2009 frei vereinbart; es verbleiben lediglich orientative Kriterien (criterios orientadores), die hauptsächlich zur Kostenfestsetzung (tasación de costas) herangezogen werden. Stundensätze reichen von €100 in regionalen Kanzleien bis zu €450+ in Wirtschaftskanzleien in Madrid und Barcelona. Justicia gratuita (Ley 1/1996) bietet bedürftigkeitsgeprüfte Prozesskostenhilfe, die Abogado-, Procurador- und Gerichtsgebühren abdeckt: Ab 2026 liegt die Schwelle bei etwa dem Doppelten des IPREM (rund €1.200 pro Monat für einen alleinstehenden Erwachsenen), mit höheren Obergrenzen für größere Familien oder Opfer von geschlechtsspezifischer Gewalt, Terrorismus oder Menschenhandel, die unabhängig vom Einkommen qualifiziert sind. Anträge werden bei der örtlichen Comisión de Asistencia Jurídica Gratuita über das Colegio eingereicht.",
      "fr": "Les honoraires sont librement convenus en Espagne depuis que la Ley Ómnibus 25/2009 a aboli les barèmes obligatoires des barreaux ; seuls des critères orientatifs (criterios orientadores) subsistent, utilisés principalement pour la taxation des frais (tasación de costas). Les taux horaires varient de €100 dans les cabinets régionaux à €450+ dans les cabinets d'affaires de Madrid et Barcelone. La justicia gratuita (Ley 1/1996) offre une aide juridictionnelle sous conditions de ressources couvrant les honoraires d'abogado, de procurador et les frais de justice : à partir de 2026, le seuil est d'environ deux fois l'IPREM (environ €1,200 par mois pour un adulte seul), avec des plafonds plus élevés pour les familles nombreuses ou les victimes de violence de genre, de terrorisme ou de traite des êtres humains, qui sont éligibles quel que soit leur revenu. Les demandes sont déposées auprès de la Comisión de Asistencia Jurídica Gratuita locale par l'intermédiaire du colegio.",
      "it": "Gli onorari sono liberamente concordati in Spagna da quando la Ley Ómnibus 25/2009 ha abolito le tariffe forensi obbligatorie; rimangono solo criteri orientativi (criterios orientadores), utilizzati principalmente per la tassazione delle spese (tasación de costas). Le tariffe orarie vanno da €100 negli studi regionali a €450+ negli studi d'affari di Madrid e Barcellona. La Justicia gratuita (Ley 1/1996) fornisce assistenza legale basata sul reddito che copre le spese di abogado, procurador e tribunale: a partire dal 2026 la soglia è circa il doppio dell'IPREM (circa €1.200 al mese per un adulto single), con massimali più elevati per famiglie più numerose o vittime di violenza di genere, terrorismo o tratta di esseri umani, che si qualificano indipendentemente dal reddito. Le domande vengono presentate alla Comisión de Asistencia Jurídica Gratuita locale tramite il colegio."
    },
    "barAssociation": {
      "membershipRules": {
        "de": "Jeder praktizierende Abogado muss den Máster Universitario de Acceso a la Abogacía besitzen, das staatliche Examen de Acceso bestehen, in einem Colegio vereidigt werden und eine obligatorische Berufshaftpflichtversicherung abschließen. Das Estatuto General de la Abogacía Española (RD 135/2021) und der Código Deontológico regeln Ethik, Interessenkonflikte und Werbung. Werbung ist erlaubt, muss aber wahrheitsgemäß sein und die Würde des Berufsstandes respektieren; vergleichende oder reißerische Werbung bleibt verboten.",
        "fr": "Tout abogado en exercice doit être titulaire du Máster Universitario de Acceso a la Abogacía, réussir l'Examen de Acceso d'État, prêter serment devant un Colegio et souscrire une assurance responsabilité civile professionnelle obligatoire. L'Estatuto General de la Abogacía Española (RD 135/2021) et le Código Deontológico régissent l'éthique, les conflits d'intérêts et la publicité. La publicité est autorisée mais doit être véridique et respecter la dignité de la profession ; la publicité comparative ou sensationnaliste reste interdite.",
        "it": "Ogni abogado praticante deve possedere il Máster Universitario de Acceso a la Abogacía, superare l'Examen de Acceso statale, prestare giuramento presso un Colegio e avere un'assicurazione obbligatoria di responsabilità civile professionale. Lo Estatuto General de la Abogacía Española (RD 135/2021) e il Código Deontológico regolano l'etica, i conflitti e la pubblicità. La pubblicità è consentita ma deve essere veritiera e rispettare la dignità della professione; la pubblicità comparativa o sensazionalistica rimane proibita."
      }
    },
    "crossBorderEU": {
      "de": "Gemäß der Niederlassungsrichtlinie 98/5/EG, umgesetzt durch Real Decreto 936/2001 (jetzt konsolidiert in RD 135/2021), dürfen in der EU zugelassene Anwälte in Spanien unter ihrer Herkunftsbezeichnung praktizieren, nachdem sie sich bei einem spanischen Colegio registriert haben. Nach drei Jahren effektiver und regelmäßiger Praxis im spanischen Recht können sie die vollständige Integration als Abogado beantragen, ohne die staatliche Zugangsprüfung ablegen zu müssen. Kurzfristige grenzüberschreitende Dienstleistungen unterliegen der Richtlinie 77/249/EWG und den entsprechenden spanischen Vorschriften: Ein portugiesischer advogado oder französischer avocat kann beispielsweise in einer einzelnen spanischen Anhörung unter seiner Herkunftsbezeichnung auftreten und, wo vorgeschrieben, mit einem lokalen colegiado zusammenarbeiten.",
      "fr": "En vertu de la Directive d'établissement 98/5/CE, transposée par le Real Decreto 936/2001 (désormais consolidé dans le RD 135/2021), les avocats admis dans l'UE peuvent exercer en Espagne sous leur titre d'origine après s'être inscrits auprès d'un Colegio espagnol. Après trois ans de pratique effective et régulière du droit espagnol, ils peuvent demander leur pleine intégration en tant qu'abogado sans passer l'examen d'accès d'État. Les services transfrontaliers à court terme sont régis par la Directive 77/249/CEE et les règles espagnoles correspondantes : un advogado portugais ou un avocat français peut, par exemple, comparaître à une seule audience espagnole sous son titre d'origine, en collaboration avec un colegiado local lorsque cela est obligatoire.",
      "it": "Ai sensi della Direttiva di Stabilimento 98/5/CE, recepita dal Real Decreto 936/2001 (ora consolidato nel RD 135/2021), gli avvocati ammessi nell'UE possono esercitare in Spagna con il loro titolo di origine dopo essersi registrati presso un Colegio spagnolo. Dopo tre anni di pratica effettiva e regolare nel diritto spagnolo possono richiedere la piena integrazione come abogado senza sostenere l'esame di accesso statale. I servizi transfrontalieri a breve termine sono regolati dalla Direttiva 77/249/CEE e dalle corrispondenti norme spagnole: un advogado portoghese o un avocat francese possono, ad esempio, comparire in una singola udienza spagnola con il loro titolo di origine, lavorando con un colegiado locale dove obbligatorio."
    },
    "faqs": [
      {
        "q": {
          "de": "Wie bestätige ich, dass ein Abogado tatsächlich registriert ist?",
          "fr": "Comment puis-je confirmer qu'un abogado est réellement inscrit ?",
          "it": "Come posso confermare che un abogado è effettivamente registrato?"
        },
        "a": {
          "de": "Suchen Sie im konsolidierten CGAE-Verzeichnis unter abogacia.es oder im censo des jeweiligen Colegio (ICAM, ICAB usw.). Alle praktizierenden Abogados müssen colegiados ejercientes sein.",
          "fr": "Recherchez dans le recensement consolidé du CGAE sur abogacia.es ou dans le censo du Colegio pertinent (ICAM, ICAB, etc.). Tous les abogados en exercice doivent être colegiados ejercientes.",
          "it": "Cerca nel censimento consolidato del CGAE su abogacia.es o nel censo del Colegio pertinente (ICAM, ICAB, ecc.). Tutti gli abogados praticanti devono essere colegiados ejercientes."
        }
      },
      {
        "q": {
          "de": "Ist eine schriftliche Mandatsvereinbarung erforderlich?",
          "fr": "Une lettre de mission écrite est-elle requise ?",
          "it": "È richiesta una lettera di incarico scritta?"
        },
        "a": {
          "de": "Ja. Artikel 13 des Estatuto General de la Abogacía Española (RD 135/2021) verlangt eine schriftliche hoja de encargo und einen presupuesto für jedes Mandat mit einem Verbraucher.",
          "fr": "Oui. L'article 13 de l'Estatuto General de la Abogacía Española (RD 135/2021) exige une hoja de encargo et un presupuesto écrits pour toute mission avec un consommateur.",
          "it": "Sì. L'articolo 13 dello Estatuto General de la Abogacía Española (RD 135/2021) richiede un'hoja de encargo e un presupuesto scritti per qualsiasi incarico con un consumatore."
        }
      },
      {
        "q": {
          "de": "Wer hat Anspruch auf justicia gratuita?",
          "fr": "Qui est éligible à la justicia gratuita ?",
          "it": "Chi si qualifica per la justicia gratuita?"
        },
        "a": {
          "de": "Haushalte, deren Einkommen unter etwa dem Doppelten des IPREM liegt (~€1.200/Monat für einen alleinstehenden Erwachsenen im Jahr 2026), sind qualifiziert; Opfer von geschlechtsspezifischer Gewalt, Terrorismus oder Menschenhandel sind unabhängig vom Einkommen qualifiziert.",
          "fr": "Les ménages dont les revenus sont inférieurs à environ deux fois l'IPREM (environ €1,200/mois pour un adulte seul en 2026) sont éligibles ; les victimes de violence de genre, de terrorisme ou de traite des êtres humains sont éligibles quel que soit leur revenu.",
          "it": "Si qualificano i nuclei familiari al di sotto di circa il doppio dell'IPREM (circa €1.200/mese per un adulto single nel 2026); le vittime di violenza di genere, terrorismo o tratta si qualificano indipendentemente dal reddito."
        }
      },
      {
        "q": {
          "de": "Benötige ich sowohl einen Abogado als auch einen Procurador?",
          "fr": "Ai-je besoin à la fois d'un abogado et d'un procurador ?",
          "it": "Ho bisogno sia di un abogado che di un procurador?"
        },
        "a": {
          "de": "Für die meisten Berufungs- und Verfassungsverfahren ja. Für viele erstinstanzliche Zivil- und Arbeitsrechtssachen reicht seit der Verfahrensreform von 2009 ein einziger Abogado aus.",
          "fr": "Pour la plupart des procédures d'appel et constitutionnelles, oui. Pour de nombreuses affaires civiles et sociales de première instance, un seul abogado suffit depuis la réforme procédurale de 2009.",
          "it": "Per la maggior parte dei procedimenti d'appello e costituzionali, sì. Per molti casi civili e di lavoro di primo grado un singolo abogado è sufficiente dalla riforma processuale del 2009."
        }
      },
      {
        "q": {
          "de": "Kann ich einen in einem anderen EU-Land zugelassenen Anwalt beauftragen?",
          "fr": "Puis-je engager un avocat admis dans un autre pays de l'UE ?",
          "it": "Posso assumere un avvocato abilitato in un altro paese dell'UE?"
        },
        "a": {
          "de": "Ja. Die Niederlassungs- und Dienstleistungsrichtlinien erlauben die grenzüberschreitende Praxis. Für eine dauerhafte Niederlassung muss sich der Anwalt bei einem spanischen Colegio registrieren.",
          "fr": "Oui. Les Directives sur l'établissement et les services autorisent la pratique transfrontalière. Pour un établissement permanent, l'avocat doit s'inscrire auprès d'un Colegio espagnol.",
          "it": "Sì. Le Direttive di Stabilimento e Servizi consentono la pratica transfrontaliera. Per lo stabilimento permanente l'avvocato deve registrarsi presso un Colegio spagnolo."
        }
      },
      {
        "q": {
          "de": "Sind Erfolgshonorare in Spanien erlaubt?",
          "fr": "Les honoraires de résultat sont-ils autorisés en Espagne ?",
          "it": "Le parcelle di successo sono consentite in Spagna?"
        },
        "a": {
          "de": "Ja. Nach dem Urteil des Tribunal Supremo von 2008 (sentencia 4 nov. 2008) ist die cuota litis zulässig, sofern sie schriftlich frei vereinbart wird und die Grundsätze des Código Deontológico respektiert.",
          "fr": "Oui. Après l'arrêt de 2008 du Tribunal Supremo (sentencia 4 nov. 2008), la cuota litis est autorisée, à condition qu'elle soit librement convenue par écrit et qu'elle respecte les principes du Código Deontológico.",
          "it": "Sì. Dopo la sentenza del Tribunal Supremo del 2008 (sentencia 4 nov. 2008) la cuota litis è consentita, a condizione che sia liberamente concordata per iscritto e rispetti i principi del Código Deontológico."
        }
      }
    ]
  },
  "it": {},
  "pt": {}
};
