/**
 * AUTO-GENERATED by scripts/translate-country-pillars.mjs — do not edit by hand.
 *
 * Phase B8 — Full 6-locale fan-out. Holds AI-translated copies of every
 * PillarLocalized field for the 4 non-native, non-English locales per country.
 * Merged into COUNTRY_PILLARS at module load via deepMergePillar().
 *
 * Reruns of the generator only fill missing keys; native + English copy in
 * countryPillars.ts always wins.
 */

import type { EuCountryCode, LocaleCode } from "./countries";

export type GeneratedLocalized = Partial<Record<LocaleCode, string>>;

export interface GeneratedPillar {
  hero?: {
    tagline?: GeneratedLocalized;
    lede?: GeneratedLocalized;
  };
  legalSystem?: GeneratedLocalized;
  howToFindLawyer?: GeneratedLocalized;
  feesAndAid?: GeneratedLocalized;
  barAssociation?: {
    membershipRules?: GeneratedLocalized;
  };
  crossBorderEU?: GeneratedLocalized;
  faqs?: Array<{ q?: GeneratedLocalized; a?: GeneratedLocalized }>;
}

export const GENERATED_PILLAR_TRANSLATIONS: Record<EuCountryCode, GeneratedPillar> = {
  de: {},
  fr: {},
  es: {},
  it: {},
  pt: {},
};
