/**
 * AUTO-GENERATED by scripts/translate-region-intros.mjs — do not edit by hand.
 *
 * Phase B9.5 — Region-intro 6-locale fan-out overlay. Authored copy in
 * regionIntros.ts always wins; this file fills locale gaps via AI translation.
 */

import type { EuCountryCode, LocaleCode } from "./countries";

export type GeneratedRegionIntros = Partial<
  Record<EuCountryCode, Partial<Record<string, Partial<Record<LocaleCode, string>>>>>
>;

export const GENERATED_REGION_INTROS: GeneratedRegionIntros = {};
