/**
 * AUTO-GENERATED by scripts/translate-region-intros.mjs — do not edit by hand.
 *
 * Phase B9.5 — Region-intro 6-locale fan-out overlay. Authored copy in
 * regionIntros.ts always wins; this file fills locale gaps via AI translation.
 */

import type { EuCountryCode, LocaleCode } from "./countries";

export type GeneratedRegionIntros = Partial<
  Record<EuCountryCode, Partial<Record<string, Partial<Record<LocaleCode, string>>>>>
>;

export const GENERATED_REGION_INTROS: GeneratedRegionIntros = {
  "fr": {
    "ile-de-france": {
      "de": "Île-de-France ist Frankreichs wirtschaftliches und juristisches Herz, Heimat der Pariser Anwaltskammer (die größte in Europa mit ~32.000 Avocats) und des Cour d'appel de Paris, das Handels-, IP- und aufsehenerregende Strafrechtsberufungen aus der gesamten Region verhandelt. Die meisten internationalen Kanzleien und spezialisierten Berater für Finanzen, M&A und Schiedsgerichtsbarkeit sind hier ansässig.",
      "es": "Île-de-France es el corazón económico y judicial de Francia, sede del Colegio de Abogados de París (el más grande de Europa con ~32.000 abogados) y la Cour d'appel de Paris, que conoce de apelaciones comerciales, de propiedad intelectual y penales de alto perfil de toda la región. La mayoría de las firmas internacionales y los asesores especializados en finanzas, fusiones y adquisiciones (M&A) y arbitraje tienen su sede aquí.",
      "it": "L'Île-de-France è il fulcro economico e giudiziario della Francia, che ospita l'Ordine degli Avvocati di Parigi (il più grande d'Europa con circa 32.000 avvocati iscritti) e la Cour d'appel de Paris, tribunale che si occupa di appelli commerciali, di proprietà intellettuale e di casi penali di alto profilo provenienti da tutta la regione. La maggior parte degli studi legali internazionali e dei consulenti specializzati in finanza, fusioni e acquisizioni (M&A) e arbitrato ha la propria sede in questa regione.",
      "pt": "A Île-de-France é o coração económico e judicial da França, sede da Ordem dos Advogados de Paris (a maior da Europa, com cerca de 32.000 advogados) e da Cour d'appel de Paris, que julga recursos comerciais, de PI e criminais de alto perfil de toda a região. A maioria das firmas internacionais e dos consultores especializados em finanças, F&A e arbitragem estão sediados aqui."
    },
    "auvergne-rhone-alpes": {
      "de": "Auvergne-Rhône-Alpes umfasst Lyon, Grenoble, Saint-Étienne und Clermont-Ferrand. Die Cour d'appel de Lyon ist für den Teil Rhône-Alpes zuständig, während Riom Auvergne abdeckt. Starke lokale Anwaltskammern in Lyon und Grenoble sind auf Industrie-, Pharma- und Technologie-Streitigkeiten spezialisiert, die mit den Fertigungs- und Forschungsclustern der Region verbunden sind.",
      "es": "Auvergne-Rhône-Alpes abarca Lyon, Grenoble, Saint-Étienne y Clermont-Ferrand. La Cour d'appel de Lyon atiende la parte de Rhône-Alpes, mientras que Riom cubre Auvergne. Colegios de abogados locales sólidos en Lyon y Grenoble se especializan en disputas industriales, farmacéuticas y tecnológicas vinculadas a los clústeres de fabricación e investigación de la región.",
      "it": "L'Auvergne-Rhône-Alpes comprende Lione, Grenoble, Saint-Étienne e Clermont-Ferrand. La Cour d'appel de Lyon serve la parte del Rhône-Alpes, mentre Riom copre l'Auvergne. Forti ordini forensi locali a Lione e Grenoble sono specializzati in controversie industriali, farmaceutiche e tecnologiche legate ai poli manifatturieri e di ricerca della regione.",
      "pt": "Auvergne-Rhône-Alpes abrange Lyon, Grenoble, Saint-Étienne e Clermont-Ferrand. A Cour d'appel de Lyon atende a parte de Rhône-Alpes, enquanto Riom cobre Auvergne. Fortes ordens de advogados locais em Lyon e Grenoble especializam-se em litígios industriais, farmacêuticos e tecnológicos, ligados aos clusters de manufatura e pesquisa da região."
    }
  }
};
