/**
 * AUTO-GENERATED by scripts/translate-region-intros.mjs — do not edit by hand.
 *
 * Phase B9.5 — Region-intro 6-locale fan-out overlay. Authored copy in
 * regionIntros.ts always wins; this file fills locale gaps via AI translation.
 */

import type { EuCountryCode, LocaleCode } from "./countries";

export type GeneratedRegionIntros = Partial<
  Record<EuCountryCode, Partial<Record<string, Partial<Record<LocaleCode, string>>>>>
>;

export const GENERATED_REGION_INTROS: GeneratedRegionIntros = {
  "fr": {
    "ile-de-france": {
      "de": "Île-de-France ist Frankreichs wirtschaftliches und juristisches Herz, Heimat der Pariser Anwaltskammer (die größte in Europa mit ~32.000 Avocats) und des Cour d'appel de Paris, das Handels-, IP- und aufsehenerregende Strafrechtsberufungen aus der gesamten Region verhandelt. Die meisten internationalen Kanzleien und spezialisierten Berater für Finanzen, M&A und Schiedsgerichtsbarkeit sind hier ansässig.",
      "es": "Île-de-France es el corazón económico y judicial de Francia, sede del Colegio de Abogados de París (el más grande de Europa con ~32.000 abogados) y la Cour d'appel de Paris, que conoce de apelaciones comerciales, de propiedad intelectual y penales de alto perfil de toda la región. La mayoría de las firmas internacionales y los asesores especializados en finanzas, fusiones y adquisiciones (M&A) y arbitraje tienen su sede aquí.",
      "it": "L'Île-de-France è il fulcro economico e giudiziario della Francia, che ospita l'Ordine degli Avvocati di Parigi (il più grande d'Europa con circa 32.000 avvocati iscritti) e la Cour d'appel de Paris, tribunale che si occupa di appelli commerciali, di proprietà intellettuale e di casi penali di alto profilo provenienti da tutta la regione. La maggior parte degli studi legali internazionali e dei consulenti specializzati in finanza, fusioni e acquisizioni (M&A) e arbitrato ha la propria sede in questa regione.",
      "pt": "A Île-de-France é o coração económico e judicial da França, sede da Ordem dos Advogados de Paris (a maior da Europa, com cerca de 32.000 advogados) e da Cour d'appel de Paris, que julga recursos comerciais, de PI e criminais de alto perfil de toda a região. A maioria das firmas internacionais e dos consultores especializados em finanças, F&A e arbitragem estão sediados aqui."
    },
    "auvergne-rhone-alpes": {
      "de": "Auvergne-Rhône-Alpes umfasst Lyon, Grenoble, Saint-Étienne und Clermont-Ferrand. Die Cour d'appel de Lyon ist für den Teil Rhône-Alpes zuständig, während Riom Auvergne abdeckt. Starke lokale Anwaltskammern in Lyon und Grenoble sind auf Industrie-, Pharma- und Technologie-Streitigkeiten spezialisiert, die mit den Fertigungs- und Forschungsclustern der Region verbunden sind.",
      "es": "Auvergne-Rhône-Alpes abarca Lyon, Grenoble, Saint-Étienne y Clermont-Ferrand. La Cour d'appel de Lyon atiende la parte de Rhône-Alpes, mientras que Riom cubre Auvergne. Colegios de abogados locales sólidos en Lyon y Grenoble se especializan en disputas industriales, farmacéuticas y tecnológicas vinculadas a los clústeres de fabricación e investigación de la región.",
      "it": "L'Auvergne-Rhône-Alpes comprende Lione, Grenoble, Saint-Étienne e Clermont-Ferrand. La Cour d'appel de Lyon serve la parte del Rhône-Alpes, mentre Riom copre l'Auvergne. Forti ordini forensi locali a Lione e Grenoble sono specializzati in controversie industriali, farmaceutiche e tecnologiche legate ai poli manifatturieri e di ricerca della regione.",
      "pt": "Auvergne-Rhône-Alpes abrange Lyon, Grenoble, Saint-Étienne e Clermont-Ferrand. A Cour d'appel de Lyon atende a parte de Rhône-Alpes, enquanto Riom cobre Auvergne. Fortes ordens de advogados locais em Lyon e Grenoble especializam-se em litígios industriais, farmacêuticos e tecnológicos, ligados aos clusters de manufatura e pesquisa da região."
    },
    "provence-alpes-cote-dazur": {
      "de": "Provence-Alpes-Côte d'Azur (PACA) umfasst Marseille, Nizza, Toulon und Aix-en-Provence. Die Cour d'appel d'Aix-en-Provence gehört zu den meistfrequentierten in Frankreich, mit einer erheblichen Anzahl von Fällen in den Bereichen Seerecht, Immobilien und grenzüberschreitendes Familienrecht, bedingt durch die Mittelmeerküste und die italienische Grenze.",
      "es": "Provenza-Alpes-Costa Azul (PACA) abarca Marsella, Niza, Tolón y Aix-en-Provence. La Cour d'appel d'Aix-en-Provence se encuentra entre las más activas de Francia, con una importante carga de casos marítimos, inmobiliarios y de familia transfronterizos, impulsada por la costa mediterránea y la frontera italiana.",
      "it": "La Provence-Alpi-Costa Azzurra (PACA) comprende Marsiglia, Nizza, Tolone e Aix-en-Provence. La Cour d'appel d'Aix-en-Provence è tra le più attive in Francia, con un significativo carico di casi marittimi, immobiliari e familiari transfrontalieri, dovuto alla costa mediterranea e al confine italiano.",
      "pt": "Provence-Alpes-Côte d'Azur (PACA) abrange Marselha, Nice, Toulon e Aix-en-Provence. A Cour d'appel d'Aix-en-Provence está entre as mais movimentadas da França, com uma carga de casos significativa em direito marítimo, imobiliário e de família transfronteiriço, impulsionada pela costa Mediterrânea e pela fronteira italiana."
    },
    "occitanie": {
      "de": "Okzitanien umfasst Toulouse, Montpellier, Nîmes und Perpignan. Toulouse beherbergt eine aktive Anwaltschaft, die die Luft- und Raumfahrt- sowie die Digitalbranche bedient; Montpellier ist auf Agrar- und Umweltrecht spezialisiert. Die Cours d'appel de Toulouse, Montpellier und Nîmes teilen sich die gerichtliche Arbeitslast der Region.",
      "es": "Occitania agrupa a Toulouse, Montpellier, Nîmes y Perpiñán. Toulouse alberga un colegio de abogados activo que atiende a los sectores aeroespacial y digital; Montpellier se especializa en derecho agrario y ambiental. Los Cours d'appel de Toulouse, Montpellier y Nîmes comparten la carga de trabajo judicial de la región.",
      "it": "L'Occitania raggruppa Tolosa, Montpellier, Nîmes e Perpignan. Tolosa ospita un foro attivo al servizio dei settori aerospaziale e digitale; Montpellier è specializzata in diritto agrario e ambientale. Le Corti d'appello di Tolosa, Montpellier e Nîmes condividono il carico di lavoro giudiziario della regione.",
      "pt": "Occitanie agrupa Toulouse, Montpellier, Nîmes e Perpignan. Toulouse acolhe uma ordem de advogados ativa que serve os setores aeroespacial e digital; Montpellier especializa-se em direito agrícola e ambiental. Os Cours d'appel de Toulouse, Montpellier e Nîmes partilham a carga de trabalho judicial da região."
    },
    "nouvelle-aquitaine": {
      "de": "Nouvelle-Aquitaine, mit Bordeaux als Ankerpunkt, erstreckt sich vom Atlantik bis zur spanischen Grenze. Die Cour d'appel de Bordeaux befasst sich mit Streitigkeiten aus der Weinindustrie, grenzüberschreitenden Familienstreitigkeiten und spanienbezogenen Handelsstreitigkeiten. Limoges und Pau beherbergen weitere Berufungsgerichte.",
      "es": "Nueva Aquitania, con Burdeos como su ancla, se extiende desde el Atlántico hasta la frontera española. La Cour d'appel de Bordeaux gestiona disputas comerciales relacionadas con la industria vitivinícola, asuntos familiares transfronterizos y litigios comerciales vinculados a España. Limoges y Pau albergan jurisdicciones de apelación secundarias.",
      "it": "La Nouvelle-Aquitaine, con Bordeaux come fulcro, si estende dall'Atlantico al confine spagnolo. La Cour d'appel de Bordeaux gestisce controversie del settore vinicolo, familiari transfrontaliere e commerciali legate alla Spagna. Limoges e Pau ospitano giurisdizioni d'appello secondarie.",
      "pt": "Nouvelle-Aquitaine, com Bordéus como seu ponto de ancoragem, estende-se do Atlântico até à fronteira espanhola. A Cour d'appel de Bordeaux trata de disputas da indústria vinícola, familiares transfronteiriças e comerciais ligadas à Espanha. Limoges e Pau acolhem jurisdições de apelação secundárias."
    },
    "hauts-de-france": {
      "de": "Hauts-de-France (Lille, Amiens) liegt an der belgischen Grenze und am Ärmelkanal. Die Cour d'appel de Douai ist das regionale Berufungsgericht; die Anwaltskammer Lille ist die größte außerhalb der Île-de-France und befasst sich mit komplexen Logistik-, Transport- und grenzüberschreitenden Handelsstreitigkeiten im Ärmelkanalbereich.",
      "es": "Hauts-de-France (Lille, Amiens) se encuentra en la frontera belga y el Canal de la Mancha. La Cour d'appel de Douai es la corte de apelación regional; el Colegio de Abogados de Lille es el más grande fuera de Île-de-France y gestiona litigios comerciales de gran volumen en logística, transporte y transfronterizos (a través del Canal de la Mancha).",
      "it": "Hauts-de-France (Lille, Amiens) si trova al confine belga e sul Canale della Manica. La Cour d'appel de Douai è la corte d'appello regionale; il foro di Lille è il più grande al di fuori dell'Île-de-France e gestisce contenziosi commerciali complessi in materia di logistica, trasporti e trans-Manica.",
      "pt": "Hauts-de-France (Lille, Amiens) situa-se na fronteira belga e no Canal da Mancha. A Cour d'appel de Douai é o tribunal de recurso regional; a ordem dos advogados de Lille é a maior fora de Île-de-France e lida com litígios comerciais pesados de logística, transporte e trans-Mancha."
    },
    "grand-est": {
      "de": "Grand Est umfasst Straßburg, Reims, Metz und Nancy. Die Anwaltskammer von Straßburg ist einzigartig in Frankreich: Anwälte können vor dem Europäischen Gerichtshof für Menschenrechte plädieren, und lokale Gerichte wenden ein besonderes droit local d'Alsace-Moselle an, das vom deutschen Bürgerlichen Gesetzbuch in Bas-Rhin, Haut-Rhin und Moselle ererbt wurde.",
      "it": "Il Grand Est comprende Strasburgo, Reims, Metz e Nancy. L'ordine degli avvocati di Strasburgo è unico in Francia: gli avvocati possono patrocinare dinanzi alla Corte europea dei diritti dell'uomo, e i tribunali locali applicano un particolare droit local d'Alsace-Moselle ereditato dal codice civile tedesco nel Basso Reno, nell'Alto Reno e nella Mosella.",
      "pt": "Grand Est abrange Estrasburgo, Reims, Metz e Nancy. A Ordem dos Advogados de Estrasburgo é única na França: advogados podem advogar perante o Tribunal Europeu dos Direitos Humanos, e os tribunais locais aplicam um direito local particular da Alsácia-Mosela, herdado do código civil alemão em Bas-Rhin, Haut-Rhin e Moselle.",
      "es": "Grand Est abarca Estrasburgo, Reims, Metz y Nancy. El colegio de abogados de Estrasburgo es único en Francia: los abogados pueden litigar ante el Tribunal Europeo de Derechos Humanos, y los tribunales locales aplican un particular droit local d'Alsace-Moselle heredado del código civil alemán en Bajo Rin, Alto Rin y Mosela."
    },
    "pays-de-la-loire": {
      "de": "Pays de la Loire ist durch Nantes und Angers geprägt. Die Cour d'appel de Rennes deckt die Region zusammen mit der Bretagne ab. Starke Spezialisierungen in den Bereichen Schifffahrt, Agrarwirtschaft und Herstellung von Luft- und Raumfahrtkomponenten.",
      "es": "Pays de la Loire está anclada por Nantes y Angers. La Cour d'appel de Rennes cubre la región junto con Bretaña. Fuertes especializaciones en transporte marítimo, agronegocios y fabricación de componentes aeroespaciales.",
      "it": "I Paesi della Loira sono caratterizzati da Nantes e Angers. La Cour d'appel de Rennes copre la regione insieme alla Bretagna. Forti specializzazioni nel settore marittimo, nell'agroalimentare e nella produzione di componenti aerospaziali.",
      "pt": "Pays de la Loire é ancorada por Nantes e Angers. A Cour d'appel de Rennes abrange a região juntamente com a Bretanha. Fortes especializações em transporte marítimo, agronegócio e fabricação de componentes aeroespaciais."
    },
    "bretagne": {
      "de": "Die Bretagne umfasst Rennes, Brest, Quimper und Saint-Brieuc. Die Cour d'appel de Rennes ist das regionale Berufungsgericht; die Anwaltskammer von Rennes bearbeitet eine hohe Anzahl von Fällen im Öffentlichen Recht und in der Universitätsforschung, während Brest sich auf See- und Marineangelegenheiten spezialisiert hat.",
      "es": "Bretaña (Bretagne) abarca Rennes, Brest, Quimper y Saint-Brieuc. La Cour d'appel de Rennes es el tribunal de apelación regional; el Colegio de Abogados de Rennes gestiona una gran carga de casos de derecho público e investigación universitaria, mientras que Brest se especializa en asuntos marítimos y navales.",
      "it": "La Bretagna (Bretagne) comprende Rennes, Brest, Quimper e Saint-Brieuc. La Cour d'appel de Rennes è la corte d'appello regionale; il foro di Rennes gestisce un carico significativo di casi di diritto pubblico e controversie legate alla ricerca universitaria, mentre Brest è specializzata in questioni marittime e navali.",
      "pt": "A Bretanha (Bretagne) inclui Rennes, Brest, Quimper e Saint-Brieuc. A Cour d'appel de Rennes é o tribunal de apelação regional. A ordem dos advogados de Rennes lida com muitos casos de direito público e pesquisa universitária, enquanto Brest se foca em assuntos marítimos e navais."
    },
    "normandie": {
      "de": "Die Normandie umfasst Rouen, Caen und Le Havre. Die Cour d'appel de Rouen bearbeitet Handels- und Seerechtliche Berufungen; Le Havre ist einer der größten Containerhäfen Frankreichs, was zu erheblichen Transport- und Zollstreitigkeiten führt.",
      "es": "Normandía (Normandie) abarca Rouen, Caen y Le Havre. La Cour d'appel de Rouen gestiona apelaciones comerciales y marítimas; Le Havre es uno de los puertos de contenedores más grandes de Francia, generando litigios significativos en transporte y aduanas.",
      "it": "La Normandia comprende Rouen, Caen e Le Havre. La Cour d'appel de Rouen gestisce gli appelli commerciali e marittimi; Le Havre è uno dei porti container più grandi della Francia, generando un contenzioso significativo in materia di trasporti e dogane.",
      "pt": "A Normandia abrange Rouen, Caen e Le Havre. A Cour d'appel de Rouen trata de recursos comerciais e marítimos; Le Havre é um dos maiores portos de contentores da França, gerando litígios significativos de transporte e alfandegários."
    },
    "bourgogne-franche-comte": {
      "de": "Bourgogne-Franche-Comté vereint die Regionen Burgund und Franche-Comté um Dijon und Besançon. Die Cour d'appel de Dijon ist für den Großteil des Gebiets zuständig, wobei Streitigkeiten im Weinbau, in der Uhrmacherei (nahe der Schweizer Grenze) und an Universitäten die Falllisten dominieren.",
      "es": "Bourgogne-Franche-Comté une las regiones de Borgoña y Franco Condado en torno a Dijon y Besançon. La Cour d'appel de Dijon atiende la mayor parte del territorio, con disputas relacionadas con la viticultura, la relojería (cerca de la frontera suiza) y las universidades dominando la lista de casos.",
      "it": "La Bourgogne-Franche-Comté unisce le regioni della Borgogna e della Franca Contea attorno a Digione e Besançon. La Cour d'appel de Dijon serve la maggior parte del territorio, con controversie legate alla viticoltura, all'orologeria (vicino al confine svizzero) e all'università che dominano il ruolo.",
      "pt": "Bourgogne-Franche-Comté une as regiões da Borgonha e do Franco-Condado em torno de Dijon e Besançon. A Cour d'appel de Dijon atende a maior parte do território, com disputas relacionadas à viticultura, relojoaria (perto da fronteira suíça) e questões universitárias dominando a pauta."
    },
    "centre-val-de-loire": {
      "de": "Centre-Val de Loire (Orléans, Tours, Bourges) untersteht der Cour d'appel d'Orléans. Kleinere Kammern bearbeiten Agrarwirtschaft, Pharma (Tours) und Immobilienstreitigkeiten um Loire-Schlösser.",
      "es": "Centre-Val de Loire (Orléans, Tours, Bourges) está servido por la Cour d'appel d'Orléans. Colegios de abogados más pequeños gestionan agronegocios, productos farmacéuticos (Tours) y disputas de propiedad de monumentos históricos en torno a los castillos del Valle del Loira.",
      "it": "Il Centre-Val de Loire (Orléans, Tours, Bourges) è servito dalla Cour d'appel d'Orléans. Studi legali più piccoli si occupano di agroalimentare, prodotti farmaceutici (Tours) e controversie immobiliari relative a monumenti storici intorno ai châteaux della Valle della Loira.",
      "pt": "Centre-Val de Loire (Orléans, Tours, Bourges) é servido pela Cour d'appel d'Orléans. Pequenas ordens de advogados lidam com agronegócio, produtos farmacêuticos (Tours) e litígios de propriedade de monumentos históricos em torno dos châteaux do Vale do Loire."
    },
    "corse": {
      "es": "Córcega (Corse) tiene su propia Cour d'appel de Bastia. Los colegios de abogados locales en Ajaccio y Bastia gestionan una alta proporción de asuntos inmobiliarios y de derecho de familia vinculados a la historia de la tenencia de la tierra de la isla (el 'arrêté Miot' y la indivisión continuada)."
    }
  }
};
