import Head from "@/components/seo/Head";
import ContentPageLayout from "@/components/layout/ContentPageLayout";

export default function TermsOfServicePage() {
  return (
    <>
      <Head
        title="Terms of Service — LegallySpoken"
        description="Read LegallySpoken's terms of service. By using our site, you agree to these terms governing your use of our legal tools and content."
      />
      <ContentPageLayout
        title="Terms of Service"
        subtitle="The terms and conditions governing your use of LegallySpoken."
        breadcrumbs={[{ label: "Terms of Service" }]}
        metaTitle="Terms of Service — LegallySpoken"
        metaDescription="Read LegallySpoken's terms of service governing your use of our legal tools and content."
      >
        <div className="prose dark:prose-invert max-w-none prose-headings:font-serif">
          <h2>Acceptance of Terms</h2>
          <p>
            By accessing or using LegallySpoken ("the Site"), you agree to be bound by these Terms of Service. If
            you do not agree to these terms, please do not use the Site.
          </p>

          <h2>Description of Service</h2>
          <p>
            LegallySpoken provides free online legal tools, calculators, document generators, and educational
            content. These tools are designed to provide general legal information and should not be considered a
            substitute for professional legal advice.
          </p>

          <h2>User Accounts</h2>
          <p>
            Some features require creating an account. You are responsible for maintaining the confidentiality of
            your account credentials and for all activities under your account. You agree to provide accurate
            information when creating your account and to notify us immediately of any unauthorized use.
          </p>

          <h2>Acceptable Use</h2>
          <p>You agree not to:</p>
          <ul>
            <li>Use the Site for any unlawful purpose or in violation of any applicable laws</li>
            <li>Attempt to gain unauthorized access to any part of the Site or its systems</li>
            <li>Use automated tools to scrape, crawl, or extract data from the Site without permission</li>
            <li>Interfere with or disrupt the Site's infrastructure or other users' access</li>
            <li>Upload malicious content, viruses, or harmful code</li>
            <li>Impersonate any person or entity, or misrepresent your affiliation</li>
          </ul>

          <h2>Intellectual Property</h2>
          <p>
            All content on LegallySpoken, including text, graphics, logos, tool designs, and software, is the
            property of LegallySpoken or its licensors and is protected by copyright and other intellectual property
            laws. You may use the Site for personal, non-commercial purposes. Documents generated by our tools are
            yours to use, but the tool interfaces and underlying code remain our property.
          </p>

          <h2>Generated Content</h2>
          <p>
            Documents and analyses generated by our tools are provided as templates and starting points. You are
            solely responsible for reviewing, customizing, and verifying any generated content before use.
            LegallySpoken makes no guarantees regarding the legal validity or enforceability of generated documents.
          </p>

          <h2>Limitation of Liability</h2>
          <p>
            To the maximum extent permitted by law, LegallySpoken and its owners, employees, and contributors shall
            not be liable for any indirect, incidental, special, consequential, or punitive damages arising out of
            your use of or inability to use the Site. Our total liability for any claim arising from your use of the
            Site shall not exceed the amount you paid us, if any, in the 12 months preceding the claim.
          </p>

          <h2>Disclaimer of Warranties</h2>
          <p>
            The Site and its tools are provided "as is" and "as available" without warranties of any kind, whether
            express or implied. We disclaim all warranties, including but not limited to implied warranties of
            merchantability, fitness for a particular purpose, and non-infringement.
          </p>

          <h2>Indemnification</h2>
          <p>
            You agree to indemnify and hold harmless LegallySpoken and its owners, employees, and contributors from
            any claims, damages, losses, or expenses arising out of your use of the Site, your violation of these
            terms, or your violation of any third-party rights.
          </p>

          <h2>Termination</h2>
          <p>
            We reserve the right to suspend or terminate your access to the Site at any time, with or without cause,
            and with or without notice. Upon termination, your right to use the Site ceases immediately.
          </p>

          <h2>Governing Law</h2>
          <p>
            These Terms of Service shall be governed by and construed in accordance with the laws of the United
            States, without regard to conflict of law principles. Any disputes arising under these terms shall be
            resolved in the courts of competent jurisdiction.
          </p>

          <h2>Changes to These Terms</h2>
          <p>
            We may revise these Terms of Service at any time. Changes take effect when posted on the Site. Your
            continued use of the Site after changes are posted constitutes acceptance of the revised terms.
          </p>

          <h2>Contact</h2>
          <p>
            Questions about these terms? Contact us at{" "}
            <a href="mailto:legal@legallyspoken.com" className="text-accent">
              legal@legallyspoken.com
            </a>.
          </p>

          <p className="text-muted-foreground text-sm mt-8">
            <em>Last updated: March 2026</em>
          </p>
        </div>
      </ContentPageLayout>
    </>
  );
}
